; Generated by nes-pascal for program BackgroundUpdates
; Mapper 0, 32 KiB PRG-ROM, 8 KiB CHR-ROM

.segment "HEADER"
    .byte "NES", $1A
    .byte 2                  ; PRG-ROM banks, 16 KiB each
    .byte 1                  ; CHR-ROM banks, 8 KiB each
    .byte $00                ; mapper and mirroring flags
    .byte $00                ; mapper upper bits
    .byte $00, $00, $00, $00, $00, $00, $00, $00

.segment "ZERO_PAGE_RUNTIME": zeropage
; Runtime: frame synchronization state, isolated from compiler temporaries
runtime_frame_counter: .res 1 ; $0000: volatile 8-bit counter incremented once by each NMI
runtime_frame_ready: .res 1 ; $0001: advisory frame-ready signal consumed by main frame waits
runtime_last_processed_frame: .res 1 ; $0002: persistent update-loop frame baseline
runtime_controller_1_current: .res 1 ; $0003: controller 1 state for the newest processed frame
runtime_controller_1_previous: .res 1 ; $0004: controller 1 state for the preceding processed frame
runtime_controller_2_current: .res 1 ; $0005: controller 2 state for the newest processed frame
runtime_controller_2_previous: .res 1 ; $0006: controller 2 state for the preceding processed frame
runtime_controller_polled_frame: .res 1 ; $0007: frame counter value of the most recent controller poll
runtime_controller_poll_valid: .res 1 ; $0008: distinguishes an initial zero byte from a completed frame-zero poll

.segment "ZERO_PAGE_TEMPORARIES": zeropage
; Compiler: mandatory expression and loop storage in Zero Page
    ; no compiler temporaries required

.segment "ZERO_PAGE_VARIABLES": zeropage
; Source: optional global-variable promotion with regular-RAM fallback
variable_X: .res 1 ; $0080: X: byte
variable_Y: .res 1 ; $0081: Y: byte
variable_Tile: .res 1 ; $0082: Tile: byte


.segment "RUNTIME_DATA"
; Runtime: regular-RAM state kept separate from user variables
runtime_ppuctrl_shadow: .res 1 ; $0200: authoritative PPUCTRL value restored each NMI
runtime_ppumask_shadow: .res 1 ; $0201: authoritative PPUMASK value restored each NMI
runtime_scroll_x_shadow: .res 1 ; $0202: authoritative horizontal scroll restored each NMI
runtime_scroll_y_shadow: .res 1 ; $0203: authoritative vertical scroll restored each NMI
runtime_background_shadow: .res 960 ; $0204: 960-byte confirmed PPU tile shadow for nametable 0
runtime_background_queue_ready: .res 4 ; $05C4: four-slot background update queue atomic publication flags
runtime_background_queue_high: .res 4 ; $05C8: four-slot background update queue PPU address high bytes
runtime_background_queue_low: .res 4 ; $05CC: four-slot background update queue PPU address low bytes
runtime_background_queue_value: .res 4 ; $05D0: four-slot background update queue PPU data bytes
runtime_background_queue_overflow: .res 1 ; $05D4: sticky flag set when all four update slots are occupied
runtime_background_queue_cancel_lock: .res 1 ; $05D5: atomic cancellation lock checked by the NMI uploader
runtime_background_x: .res 1 ; $05D6: background helper X input
runtime_background_y: .res 1 ; $05D7: background helper Y input
runtime_background_pending_value: .res 1 ; $05D8: background helper byte input
runtime_background_index_low: .res 1 ; $05D9: computed nametable tile offset and confirmed-shadow byte offset
runtime_background_index_page: .res 1 ; $05DA: computed nametable address page and confirmed-shadow page index

.segment "USER_VARIABLES"
; Source: non-promoted variables and all parameters in regular CPU RAM
variable_Overflowed: .res 1 ; $05DB: Overflowed: boolean

.segment "CODE"

; Interrupt handlers
NMI:
    pha
    txa
    pha
    tya
    pha

    inc runtime_frame_counter ; volatile 8-bit counter, wraps modulo 256
    lda #$01
    sta runtime_frame_ready   ; advisory; frame counter is authoritative

    ; Runtime: consume at most four queued background writes in VBlank
    jsr runtime_upload_queued_background

    ; Runtime: authoritative final PPU state after all VBlank work
    bit $2002               ; reset the shared PPU write latch
    lda runtime_ppuctrl_shadow
    sta $2000
    lda runtime_scroll_x_shadow
    sta $2005               ; scroll X (first write)
    lda runtime_scroll_y_shadow
    sta $2005               ; scroll Y (second write)
    lda runtime_ppumask_shadow
    sta $2001

    pla
    tay
    pla
    tax
    pla
    rti

IRQ:
    rti

; Source: implicit NES runtime initialization
RESET:
    sei
    cld
    ldx #$40
    stx $4017               ; disable frame counter IRQ
    ldx #$FF
    txs
    inx                     ; X = 0
    stx $2000               ; disable NMI
    stx $2001               ; disable rendering
    stx $4010               ; disable DMC IRQ
    bit $2002               ; clear the vblank latch

@wait_vblank_1:
    bit $2002
    bpl @wait_vblank_1

    txa
@clear_ram:
    sta $0000, x
    sta $0100, x
    sta $0200, x
    sta $0300, x
    sta $0400, x
    sta $0500, x
    sta $0600, x
    sta $0700, x
    inx
    bne @clear_ram

@wait_vblank_2:
    bit $2002
    bpl @wait_vblank_2

; Runtime: establish a zeroed nametable matching the confirmed shadow
    bit $2002               ; reset PPU address latch
    lda #$20
    sta $2006
    lda #$00
    sta $2006
    ldx #$00
@clear_background_page_0:
    sta $2007
    inx
    bne @clear_background_page_0
@clear_background_page_1:
    sta $2007
    inx
    bne @clear_background_page_1
@clear_background_page_2:
    sta $2007
    inx
    bne @clear_background_page_2
@clear_background_page_3:
    sta $2007
    inx
    bne @clear_background_page_3
; Source: X := value
    lda #$01
    sta variable_X

; Source: Y := value
    lda #$02
    sta variable_Y

; Source: Tile := value
    lda #$03
    sta variable_Tile

; Source: nes.set_background_color(value)
    lda #$3F
    sta $2006               ; universal palette address, high byte
    lda #$00
    sta $2006               ; low byte
    lda #$0F
    sta $2007

; Source: nes.run
; Runtime: defer rendering-sensitive setup to VBlank
@wait_render_vblank_0:
    bit $2002
    bpl @wait_render_vblank_0
    lda runtime_ppuctrl_shadow
    ora #$80
    sta runtime_ppuctrl_shadow ; preserve bits and enable NMI
    sta $2000
    lda runtime_scroll_x_shadow ; zero-filled default scroll X
    sta $2005
    lda runtime_scroll_y_shadow ; zero-filled default scroll Y
    sta $2005
    lda runtime_ppumask_shadow
    ora #$1E
    sta runtime_ppumask_shadow ; preserve bits and enable rendering
    sta $2001

; Source: nes.set_tile(x, y, tile)
    lda variable_X
    pha                     ; preserve X across expressions
    lda variable_Y
    pha                     ; preserve Y across tile expression
    lda variable_Tile
    sta runtime_background_pending_value
    pla
    sta runtime_background_y
    pla
    sta runtime_background_x
    jsr runtime_set_tile

; Source: Tile := value
    ; nes.get_tile(x, y): read the confirmed PPU tile shadow
    lda variable_X
    pha                     ; preserve X across Y expression
    lda variable_Y
    sta runtime_background_y
    pla
    sta runtime_background_x
    jsr runtime_get_tile
    sta variable_Tile

; Source: nes.set_attribute(x, y, value)
    lda #$00
    pha                     ; preserve X across expressions
    lda #$00
    pha                     ; preserve Y across value expression
    lda #$E4
    sta runtime_background_pending_value
    pla
    sta runtime_background_y
    pla
    sta runtime_background_x
    jsr runtime_set_attribute

; Source: Overflowed := value
    ; nes.background_updates_overflowed(): sticky queue state
    lda runtime_background_queue_overflow
    sta variable_Overflowed

; Source: nes.clear_background_updates()
    lda #$01
    sta runtime_background_queue_cancel_lock ; block whole-queue NMI consumption
    lda #$00
    sta runtime_background_queue_ready
    sta runtime_background_queue_ready + 1
    sta runtime_background_queue_ready + 2
    sta runtime_background_queue_ready + 3
    sta runtime_background_queue_cancel_lock ; release after every slot is cancelled

; Source: nes.clear_background_update_overflow()
    lda #$00
    sta runtime_background_queue_overflow

; Runtime: implicit stable loop after the main program finishes
@runtime_idle_loop:
    jmp @runtime_idle_loop

; Runtime: idempotent controller update for one newly processed frame
runtime_update_controllers:
    tax                     ; X keeps the caller's accepted frame value
    lda runtime_controller_poll_valid
    beq @controllers_need_poll
    txa
    cmp runtime_controller_polled_frame
    beq @controllers_already_current
@controllers_need_poll:
    lda #$01
    sta runtime_controller_poll_valid
    txa
    sta runtime_controller_polled_frame
    lda runtime_controller_1_current
    sta runtime_controller_1_previous
    lda runtime_controller_2_current
    sta runtime_controller_2_previous
    jsr runtime_read_controller_ports
@controllers_already_current:
    rts

; Runtime: isolated standard NES serial controller protocol
; Bit layout: A, B, Select, Start, Up, Down, Left, Right = bits 0..7.
runtime_read_controller_ports:
    lda #$01
    sta $4016               ; latch both controllers
    lda #$00
    sta $4016               ; begin serial reads
    sta runtime_controller_1_current
    sta runtime_controller_2_current
    ldx #$08
@read_controller_bits:
    lda $4016
    lsr a                   ; controller 1 serial bit -> carry
    ror runtime_controller_1_current
    lda $4017
    lsr a                   ; controller 2 serial bit -> carry
    ror runtime_controller_2_current
    dex
    bne @read_controller_bits
    rts

; Runtime: bounded four-slot background update uploader
runtime_upload_queued_background:
    lda runtime_background_queue_cancel_lock
    bne @background_upload_locked ; cancellation owns the whole queue
    ldx #$00
@background_upload_loop:
    lda runtime_background_queue_ready, x
    beq @background_upload_next
    lda #$00
    sta runtime_background_queue_ready, x ; consume only a published slot
    bit $2002               ; reset PPU address latch
    lda runtime_background_queue_high, x
    sta $2006
    lda runtime_background_queue_low, x
    sta $2006
    lda runtime_background_queue_value, x
    sta $2007
    ; Confirm a tile only after its PPU write has completed.
    lda runtime_background_queue_high, x
    cmp #$23
    bcc @confirm_tile_lower_page
    bne @background_upload_next
    lda runtime_background_queue_low, x
    cmp #$C0
    bcs @background_upload_next ; $23C0-$23FF contains attributes
    ldy runtime_background_queue_low, x
    lda runtime_background_queue_value, x
    sta runtime_background_shadow + $0300, y
    jmp @background_upload_next
@confirm_tile_lower_page:
    ldy runtime_background_queue_low, x
    cmp #$20
    beq @confirm_tile_page_0
    cmp #$21
    beq @confirm_tile_page_1
    lda runtime_background_queue_value, x
    sta runtime_background_shadow + $0200, y
    jmp @background_upload_next
@confirm_tile_page_0:
    lda runtime_background_queue_value, x
    sta runtime_background_shadow, y
    jmp @background_upload_next
@confirm_tile_page_1:
    lda runtime_background_queue_value, x
    sta runtime_background_shadow + $0100, y
@background_upload_next:
    inx
    cpx #$04
    bne @background_upload_loop
@background_upload_locked:
    rts

; Runtime: publish one PPU write only after every slot byte is complete
runtime_queue_background_write:
    ldx #$00
@background_find_slot:
    lda runtime_background_queue_ready, x
    beq @background_slot_found
    inx
    cpx #$04
    bne @background_find_slot
    lda #$01
    sta runtime_background_queue_overflow ; sticky until explicitly cleared
    sec                     ; rejected: no queue slot was modified
    rts
@background_slot_found:
    lda runtime_background_x
    sta runtime_background_queue_high, x
    lda runtime_background_y
    sta runtime_background_queue_low, x
    lda runtime_background_pending_value
    sta runtime_background_queue_value, x
    lda #$01
    sta runtime_background_queue_ready, x ; atomic publication is last
    clc                     ; accepted for the next NMI
    rts

; Runtime: validate (x: 0..31, y: 0..29) and compute y * 32 + x
runtime_prepare_tile_index:
    lda runtime_background_y
    cmp #$1E
    bcs @tile_coordinate_invalid
    and #$07
    asl a
    asl a
    asl a
    asl a
    asl a
    clc
    adc runtime_background_x
    sta runtime_background_index_low
    lda runtime_background_x
    cmp #$20
    bcs @tile_coordinate_invalid
    lda runtime_background_y
    lsr a
    lsr a
    lsr a
    sta runtime_background_index_page
    clc
    rts
@tile_coordinate_invalid:
    sec
    rts

runtime_set_tile:
    jsr runtime_prepare_tile_index
    bcs @set_tile_done
    lda runtime_background_index_page
    clc
    adc #$20
    sta runtime_background_x ; queue PPU address high byte
    lda runtime_background_index_low
    sta runtime_background_y ; queue PPU address low byte
    jsr runtime_queue_background_write
@set_tile_done:
    rts

runtime_set_attribute:
    lda runtime_background_x
    cmp #$08
    bcs @set_attribute_done
    lda runtime_background_y
    cmp #$08
    bcs @set_attribute_done
    asl a
    asl a
    asl a
    clc
    adc runtime_background_x
    clc
    adc #$C0
    sta runtime_background_y ; queue PPU address low byte
    lda #$23
    sta runtime_background_x ; queue PPU address high byte
    jsr runtime_queue_background_write
@set_attribute_done:
    rts

runtime_get_tile:
    jsr runtime_prepare_tile_index
    bcs @get_tile_invalid
    ldx runtime_background_index_low
    lda runtime_background_index_page
    beq @get_tile_page_0
    cmp #$01
    beq @get_tile_page_1
    cmp #$02
    beq @get_tile_page_2
    lda runtime_background_shadow + $0300, x
    rts
@get_tile_page_0:
    lda runtime_background_shadow, x
    rts
@get_tile_page_1:
    lda runtime_background_shadow + $0100, x
    rts
@get_tile_page_2:
    lda runtime_background_shadow + $0200, x
    rts
@get_tile_invalid:
    lda #$00
    rts


.segment "VECTORS"
    .word NMI
    .word RESET
    .word IRQ

.segment "CHR"
    .res 8192, $00          ; empty CHR-ROM
