; Generated by nes-pascal for program BooleanExpressions
; Mapper 0, 32 KiB PRG-ROM, 8 KiB CHR-ROM

.segment "HEADER"
    .byte "NES", $1A
    .byte 2                  ; PRG-ROM banks, 16 KiB each
    .byte 1                  ; CHR-ROM banks, 8 KiB each
    .byte $00                ; mapper and mirroring flags
    .byte $00                ; mapper upper bits
    .byte $00, $00, $00, $00, $00, $00, $00, $00

.segment "OAM_SHADOW"
; Runtime: page-aligned OAM DMA shadow at $0200-$02FF
runtime_oam_shadow: .res 256 ; $0200: 256-byte page copied to PPU OAM by future sprite runtime support

.segment "RUNTIME_DATA"
; Runtime: no scalar RAM symbols are required in milestone 0.3.1

.segment "TEMPORARIES"
; Compiler: reusable expression and loop storage in regular CPU RAM
expression_temporary_0: .res 1 ; $0300: reusable expression evaluation byte

.segment "USER_VARIABLES"
; Source: variable and parameter declarations in regular CPU RAM
variable_Counter: .res 1 ; $0310: Counter: byte
variable_Equal: .res 1 ; $0311: Equal: boolean
variable_Different: .res 1 ; $0312: Different: boolean
variable_Less: .res 1 ; $0313: Less: boolean
variable_Greater: .res 1 ; $0314: Greater: boolean
variable_LessOrEqual: .res 1 ; $0315: LessOrEqual: boolean
variable_GreaterOrEqual: .res 1 ; $0316: GreaterOrEqual: boolean
variable_Combined: .res 1 ; $0317: Combined: boolean
variable_BackgroundColor: .res 1 ; $0318: BackgroundColor: nes_color

.segment "CODE"

; Interrupt handlers
NMI:
    rti

IRQ:
    rti

; Source: implicit NES runtime initialization
RESET:
    sei
    cld
    ldx #$40
    stx $4017               ; disable frame counter IRQ
    ldx #$FF
    txs
    inx                     ; X = 0
    stx $2000               ; disable NMI
    stx $2001               ; disable rendering
    stx $4010               ; disable DMC IRQ
    bit $2002               ; clear the vblank latch

@wait_vblank_1:
    bit $2002
    bpl @wait_vblank_1

    txa
@clear_ram:
    sta $0000, x
    sta $0100, x
    sta $0200, x
    sta $0300, x
    sta $0400, x
    sta $0500, x
    sta $0600, x
    sta $0700, x
    inx
    bne @clear_ram

@wait_vblank_2:
    bit $2002
    bpl @wait_vblank_2

; Source: Counter := value
    lda #$0F
    sta variable_Counter

; Source: Equal := value
    ; comparison =: evaluate right operand
    lda #$10
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    beq @comparison_true_0
@comparison_false_1:
    lda #$00              ; false
    jmp @comparison_end_2
@comparison_true_0:
    lda #$01              ; true
@comparison_end_2:
    sta variable_Equal

; Source: Different := value
    ; comparison <>: evaluate right operand
    lda #$10
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    bne @comparison_true_3
@comparison_false_4:
    lda #$00              ; false
    jmp @comparison_end_5
@comparison_true_3:
    lda #$01              ; true
@comparison_end_5:
    sta variable_Different

; Source: Less := value
    ; comparison <: evaluate right operand
    lda #$10
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    bcc @comparison_true_6
@comparison_false_7:
    lda #$00              ; false
    jmp @comparison_end_8
@comparison_true_6:
    lda #$01              ; true
@comparison_end_8:
    sta variable_Less

; Source: Greater := value
    ; comparison >: evaluate right operand
    lda #$00
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    beq @comparison_false_10
    bcs @comparison_true_9
@comparison_false_10:
    lda #$00              ; false
    jmp @comparison_end_11
@comparison_true_9:
    lda #$01              ; true
@comparison_end_11:
    sta variable_Greater

; Source: LessOrEqual := value
    ; comparison <=: evaluate right operand
    lda #$10
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    bcc @comparison_true_12
    beq @comparison_true_12
@comparison_false_13:
    lda #$00              ; false
    jmp @comparison_end_14
@comparison_true_12:
    lda #$01              ; true
@comparison_end_14:
    sta variable_LessOrEqual

; Source: GreaterOrEqual := value
    ; comparison >=: evaluate right operand
    lda #$10
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    bcs @comparison_true_15
@comparison_false_16:
    lda #$00              ; false
    jmp @comparison_end_17
@comparison_true_15:
    lda #$01              ; true
@comparison_end_17:
    sta variable_GreaterOrEqual

; Source: Combined := value
    ; boolean and: evaluate left operand
    ; boolean not
    lda variable_Equal
    cmp #$00
    beq @not_true_22
    lda #$00              ; false
    jmp @not_end_23
@not_true_22:
    lda #$01              ; true
@not_end_23:
    cmp #$00
    bne @boolean_evaluate_right_18
    jmp @boolean_false_20       ; short-circuit false
@boolean_evaluate_right_18:
    ; evaluate right operand
    ; boolean or: evaluate left operand
    lda variable_Less
    cmp #$00
    beq @boolean_evaluate_right_24
    jmp @boolean_true_25        ; short-circuit true
@boolean_evaluate_right_24:
    ; evaluate right operand
    lda variable_GreaterOrEqual
    cmp #$00
    bne @boolean_true_25
@boolean_false_26:
    lda #$00              ; false
    jmp @boolean_end_27
@boolean_true_25:
    lda #$01              ; true
@boolean_end_27:
    cmp #$00
    bne @boolean_true_19
@boolean_false_20:
    lda #$00              ; false
    jmp @boolean_end_21
@boolean_true_19:
    lda #$01              ; true
@boolean_end_21:
    sta variable_Combined

; Source: BackgroundColor := value
    lda #$21
    sta variable_BackgroundColor

; Source: nes.set_background_color(value)
    lda #$3F
    sta $2006               ; universal palette address, high byte
    lda #$00
    sta $2006               ; low byte
    lda variable_BackgroundColor
    sta $2007

; Source: nes.run
    lda #$00
    sta $2005               ; scroll X
    sta $2005               ; scroll Y
    lda #$08
    sta $2001               ; enable background rendering

@main_loop:
    jmp @main_loop

.segment "VECTORS"
    .word NMI
    .word RESET
    .word IRQ

.segment "CHR"
    .res 8192, $00          ; empty CHR-ROM
