; Generated by nes-pascal for program BooleanExpressions
; Mapper 0, 32 KiB PRG-ROM, 8 KiB CHR-ROM

.segment "HEADER"
    .byte "NES", $1A
    .byte 2                  ; PRG-ROM banks, 16 KiB each
    .byte 1                  ; CHR-ROM banks, 8 KiB each
    .byte $00                ; mapper and mirroring flags
    .byte $00                ; mapper upper bits
    .byte $00, $00, $00, $00, $00, $00, $00, $00

.segment "ZERO_PAGE_RUNTIME": zeropage
; Runtime: frame synchronization state, isolated from compiler temporaries
runtime_frame_counter: .res 1 ; $0000: volatile 8-bit counter incremented once by each NMI
runtime_frame_ready: .res 1 ; $0001: advisory frame-ready signal consumed by main frame waits
runtime_last_processed_frame: .res 1 ; $0002: persistent update-loop frame baseline
runtime_controller_1_current: .res 1 ; $0003: controller 1 state for the newest processed frame
runtime_controller_1_previous: .res 1 ; $0004: controller 1 state for the preceding processed frame
runtime_controller_2_current: .res 1 ; $0005: controller 2 state for the newest processed frame
runtime_controller_2_previous: .res 1 ; $0006: controller 2 state for the preceding processed frame
runtime_controller_polled_frame: .res 1 ; $0007: frame counter value of the most recent controller poll
runtime_controller_poll_valid: .res 1 ; $0008: distinguishes an initial zero byte from a completed frame-zero poll

.segment "ZERO_PAGE_TEMPORARIES": zeropage
; Compiler: mandatory expression and loop storage in Zero Page
expression_temporary_0: .res 1 ; $0010: reusable expression evaluation byte

.segment "ZERO_PAGE_VARIABLES": zeropage
; Source: optional global-variable promotion with regular-RAM fallback
variable_Counter: .res 1 ; $0080: Counter: byte


.segment "RUNTIME_DATA"
; Runtime: regular-RAM state kept separate from user variables
runtime_ppuctrl_shadow: .res 1 ; $0200: authoritative PPUCTRL value restored each NMI
runtime_ppumask_shadow: .res 1 ; $0201: authoritative PPUMASK value restored each NMI
runtime_scroll_x_shadow: .res 1 ; $0202: authoritative horizontal scroll restored each NMI
runtime_scroll_y_shadow: .res 1 ; $0203: authoritative vertical scroll restored each NMI

.segment "USER_VARIABLES"
; Source: non-promoted variables and all parameters in regular CPU RAM
variable_Equal: .res 1 ; $0204: Equal: boolean
variable_Different: .res 1 ; $0205: Different: boolean
variable_Less: .res 1 ; $0206: Less: boolean
variable_Greater: .res 1 ; $0207: Greater: boolean
variable_LessOrEqual: .res 1 ; $0208: LessOrEqual: boolean
variable_GreaterOrEqual: .res 1 ; $0209: GreaterOrEqual: boolean
variable_Combined: .res 1 ; $020A: Combined: boolean
variable_BackgroundColor: .res 1 ; $020B: BackgroundColor: nes_color

.segment "CODE"

; Interrupt handlers
NMI:
    pha
    txa
    pha
    tya
    pha

    inc runtime_frame_counter ; volatile 8-bit counter, wraps modulo 256
    lda #$01
    sta runtime_frame_ready   ; advisory; frame counter is authoritative

    ; Runtime: authoritative final PPU state after all VBlank work
    bit $2002               ; reset the shared PPU write latch
    lda runtime_ppuctrl_shadow
    sta $2000
    lda runtime_scroll_x_shadow
    sta $2005               ; scroll X (first write)
    lda runtime_scroll_y_shadow
    sta $2005               ; scroll Y (second write)
    lda runtime_ppumask_shadow
    sta $2001

    pla
    tay
    pla
    tax
    pla
    rti

IRQ:
    rti

; Source: implicit NES runtime initialization
RESET:
    sei
    cld
    ldx #$40
    stx $4017               ; disable frame counter IRQ
    ldx #$FF
    txs
    inx                     ; X = 0
    stx $2000               ; disable NMI
    stx $2001               ; disable rendering
    stx $4010               ; disable DMC IRQ
    bit $2002               ; clear the vblank latch

@wait_vblank_1:
    bit $2002
    bpl @wait_vblank_1

    txa
@clear_ram:
    sta $0000, x
    sta $0100, x
    sta $0200, x
    sta $0300, x
    sta $0400, x
    sta $0500, x
    sta $0600, x
    sta $0700, x
    inx
    bne @clear_ram

@wait_vblank_2:
    bit $2002
    bpl @wait_vblank_2

; Source: Counter := value
    lda #$0F
    sta variable_Counter

; Source: Equal := value
    ; comparison =: evaluate right operand
    lda #$10
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    beq @comparison_true_0
@comparison_false_1:
    lda #$00              ; false
    jmp @comparison_end_2
@comparison_true_0:
    lda #$01              ; true
@comparison_end_2:
    sta variable_Equal

; Source: Different := value
    ; comparison <>: evaluate right operand
    lda #$10
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    bne @comparison_true_3
@comparison_false_4:
    lda #$00              ; false
    jmp @comparison_end_5
@comparison_true_3:
    lda #$01              ; true
@comparison_end_5:
    sta variable_Different

; Source: Less := value
    ; comparison <: evaluate right operand
    lda #$10
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    bcc @comparison_true_6
@comparison_false_7:
    lda #$00              ; false
    jmp @comparison_end_8
@comparison_true_6:
    lda #$01              ; true
@comparison_end_8:
    sta variable_Less

; Source: Greater := value
    ; comparison >: evaluate right operand
    lda #$00
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    beq @comparison_false_10
    bcs @comparison_true_9
@comparison_false_10:
    lda #$00              ; false
    jmp @comparison_end_11
@comparison_true_9:
    lda #$01              ; true
@comparison_end_11:
    sta variable_Greater

; Source: LessOrEqual := value
    ; comparison <=: evaluate right operand
    lda #$10
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    bcc @comparison_true_12
    beq @comparison_true_12
@comparison_false_13:
    lda #$00              ; false
    jmp @comparison_end_14
@comparison_true_12:
    lda #$01              ; true
@comparison_end_14:
    sta variable_LessOrEqual

; Source: GreaterOrEqual := value
    ; comparison >=: evaluate right operand
    lda #$10
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    bcs @comparison_true_15
@comparison_false_16:
    lda #$00              ; false
    jmp @comparison_end_17
@comparison_true_15:
    lda #$01              ; true
@comparison_end_17:
    sta variable_GreaterOrEqual

; Source: Combined := value
    ; boolean and: evaluate left operand
    ; boolean not
    lda variable_Equal
    cmp #$00
    beq @not_true_22
    lda #$00              ; false
    jmp @not_end_23
@not_true_22:
    lda #$01              ; true
@not_end_23:
    cmp #$00
    bne @boolean_evaluate_right_18
    jmp @boolean_false_20       ; short-circuit false
@boolean_evaluate_right_18:
    ; evaluate right operand
    ; boolean or: evaluate left operand
    lda variable_Less
    cmp #$00
    beq @boolean_evaluate_right_24
    jmp @boolean_true_25        ; short-circuit true
@boolean_evaluate_right_24:
    ; evaluate right operand
    lda variable_GreaterOrEqual
    cmp #$00
    bne @boolean_true_25
@boolean_false_26:
    lda #$00              ; false
    jmp @boolean_end_27
@boolean_true_25:
    lda #$01              ; true
@boolean_end_27:
    cmp #$00
    bne @boolean_true_19
@boolean_false_20:
    lda #$00              ; false
    jmp @boolean_end_21
@boolean_true_19:
    lda #$01              ; true
@boolean_end_21:
    sta variable_Combined

; Source: BackgroundColor := value
    lda #$21
    sta variable_BackgroundColor

; Source: nes.set_background_color(value)
    lda #$3F
    sta $2006               ; universal palette address, high byte
    lda #$00
    sta $2006               ; low byte
    lda variable_BackgroundColor
    sta $2007

; Source: nes.run
; Runtime: defer rendering-sensitive setup to VBlank
@wait_render_vblank_28:
    bit $2002
    bpl @wait_render_vblank_28
    lda runtime_ppuctrl_shadow
    ora #$80
    sta runtime_ppuctrl_shadow ; preserve bits and enable NMI
    sta $2000
    lda runtime_scroll_x_shadow ; zero-filled default scroll X
    sta $2005
    lda runtime_scroll_y_shadow ; zero-filled default scroll Y
    sta $2005
    lda runtime_ppumask_shadow
    ora #$1E
    sta runtime_ppumask_shadow ; preserve bits and enable rendering
    sta $2001

; Runtime: implicit stable loop after the main program finishes
@runtime_idle_loop:
    jmp @runtime_idle_loop

; Runtime: idempotent controller update for one newly processed frame
runtime_update_controllers:
    tax                     ; X keeps the caller's accepted frame value
    lda runtime_controller_poll_valid
    beq @controllers_need_poll
    txa
    cmp runtime_controller_polled_frame
    beq @controllers_already_current
@controllers_need_poll:
    lda #$01
    sta runtime_controller_poll_valid
    txa
    sta runtime_controller_polled_frame
    lda runtime_controller_1_current
    sta runtime_controller_1_previous
    lda runtime_controller_2_current
    sta runtime_controller_2_previous
    jsr runtime_read_controller_ports
@controllers_already_current:
    rts

; Runtime: isolated standard NES serial controller protocol
; Bit layout: A, B, Select, Start, Up, Down, Left, Right = bits 0..7.
runtime_read_controller_ports:
    lda #$01
    sta $4016               ; latch both controllers
    lda #$00
    sta $4016               ; begin serial reads
    sta runtime_controller_1_current
    sta runtime_controller_2_current
    ldx #$08
@read_controller_bits:
    lda $4016
    lsr a                   ; controller 1 serial bit -> carry
    ror runtime_controller_1_current
    lda $4017
    lsr a                   ; controller 2 serial bit -> carry
    ror runtime_controller_2_current
    dex
    bne @read_controller_bits
    rts


.segment "VECTORS"
    .word NMI
    .word RESET
    .word IRQ

.segment "CHR"
    .res 8192, $00          ; empty CHR-ROM
