; Generated by nes-pascal for program Conditionals
; Mapper 0, 32 KiB PRG-ROM, 8 KiB CHR-ROM

.segment "HEADER"
    .byte "NES", $1A
    .byte 2                  ; 2 x 16 KiB PRG-ROM
    .byte 1                  ; 1 x 8 KiB CHR-ROM
    .byte $00                ; mapper 0, horizontal mirroring
    .byte $00                ; mapper 0
    .byte $00, $00, $00, $00, $00, $00, $00, $00

.segment "BSS"
; Source: variable declarations in regular CPU RAM
variable_Counter: .res 1       ; Counter: byte
variable_Enabled: .res 1       ; Enabled: boolean
variable_BackgroundColor: .res 1       ; BackgroundColor: nes_color
expression_temporary_0: .res 1 ; expression temporary

.segment "CODE"

; Interrupt handlers
NMI:
    rti

IRQ:
    rti

; Source: implicit NES runtime initialization
RESET:
    sei
    cld
    ldx #$40
    stx $4017               ; disable frame counter IRQ
    ldx #$FF
    txs
    inx                     ; X = 0
    stx $2000               ; disable NMI
    stx $2001               ; disable rendering
    stx $4010               ; disable DMC IRQ
    bit $2002               ; clear the vblank latch

@wait_vblank_1:
    bit $2002
    bpl @wait_vblank_1

    txa
@clear_ram:
    sta $0000, x
    sta $0100, x
    sta $0200, x
    sta $0300, x
    sta $0400, x
    sta $0500, x
    sta $0600, x
    sta $0700, x
    inx
    bne @clear_ram

@wait_vblank_2:
    bit $2002
    bpl @wait_vblank_2

; Source: Counter := value
    lda #$10
    sta variable_Counter

; Source: Enabled := value
    ; comparison <=: evaluate right operand
    lda #$10
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    bcc @comparison_true_0
    beq @comparison_true_0
@comparison_false_1:
    lda #$00              ; false
    jmp @comparison_end_2
@comparison_true_0:
    lda #$01              ; true
@comparison_end_2:
    sta variable_Enabled

; Source: if condition then
    lda variable_Enabled
    cmp #$00
    bne @if_then_3
    jmp @if_else_5       ; long-branch-safe false path
@if_then_3:

; Source: BackgroundColor := value
    lda #$21
    sta variable_BackgroundColor
    jmp @if_end_4
@if_else_5:

; Source: if condition then
    ; comparison >: evaluate right operand
    lda #$10
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    beq @comparison_false_10
    bcs @comparison_true_9
@comparison_false_10:
    lda #$00              ; false
    jmp @comparison_end_11
@comparison_true_9:
    lda #$01              ; true
@comparison_end_11:
    cmp #$00
    bne @if_then_6
    jmp @if_else_8       ; long-branch-safe false path
@if_then_6:

; Source: BackgroundColor := value
    lda #$16
    sta variable_BackgroundColor
    jmp @if_end_7
@if_else_8:

; Source: BackgroundColor := value
    lda #$0F
    sta variable_BackgroundColor
@if_end_7:
@if_end_4:

; Source: nes.set_background_color(value)
    lda #$3F
    sta $2006               ; universal palette address, high byte
    lda #$00
    sta $2006               ; low byte
    lda variable_BackgroundColor
    sta $2007

; Source: nes.run
    lda #$00
    sta $2005               ; scroll X
    sta $2005               ; scroll Y
    lda #$08
    sta $2001               ; enable background rendering

@main_loop:
    jmp @main_loop

.segment "VECTORS"
    .word NMI
    .word RESET
    .word IRQ

.segment "CHR"
    .res 8192, $00          ; empty CHR-ROM
