; Generated by nes-pascal for program ControllerInput
; Mapper 0, 32 KiB PRG-ROM, 8 KiB CHR-ROM

.segment "HEADER"
    .byte "NES", $1A
    .byte 2                  ; PRG-ROM banks, 16 KiB each
    .byte 1                  ; CHR-ROM banks, 8 KiB each
    .byte $00                ; mapper and mirroring flags
    .byte $00                ; mapper upper bits
    .byte $00, $00, $00, $00, $00, $00, $00, $00

.segment "ZERO_PAGE_RUNTIME": zeropage
; Runtime: frame synchronization state, isolated from compiler temporaries
runtime_frame_counter: .res 1 ; $0000: volatile 8-bit counter incremented once by each NMI
runtime_frame_ready: .res 1 ; $0001: advisory frame-ready signal consumed by main frame waits
runtime_last_processed_frame: .res 1 ; $0002: persistent update-loop frame baseline
runtime_controller_1_current: .res 1 ; $0003: controller 1 state for the newest processed frame
runtime_controller_1_previous: .res 1 ; $0004: controller 1 state for the preceding processed frame
runtime_controller_2_current: .res 1 ; $0005: controller 2 state for the newest processed frame
runtime_controller_2_previous: .res 1 ; $0006: controller 2 state for the preceding processed frame
runtime_controller_polled_frame: .res 1 ; $0007: frame counter value of the most recent controller poll
runtime_controller_poll_valid: .res 1 ; $0008: distinguishes an initial zero byte from a completed frame-zero poll

.segment "ZERO_PAGE_TEMPORARIES": zeropage
; Compiler: mandatory expression and loop storage in Zero Page
    ; no compiler temporaries required

.segment "ZERO_PAGE_VARIABLES": zeropage
; Source: optional global-variable promotion with regular-RAM fallback
variable_PlayerX: .res 1 ; $0080: PlayerX: byte
variable_PlayerY: .res 1 ; $0081: PlayerY: byte
variable_PlayerTile: .res 1 ; $0082: PlayerTile: byte
variable_MovementSpeed: .res 1 ; $0083: MovementSpeed: byte
variable_WrapAtEdges: .res 1 ; $0084: WrapAtEdges: boolean

.segment "OAM_SHADOW"
; Runtime: page-aligned OAM DMA shadow at $0200-$02FF
runtime_oam_shadow: .res 256 ; $0200: 256-byte page copied to PPU OAM by runtime sprite support

.segment "RUNTIME_DATA"
; Runtime: regular-RAM state kept separate from user variables
runtime_sprite_zero_pending_x: .res 1 ; $0300: staged sprite 0 X coordinate
runtime_sprite_zero_pending_y: .res 1 ; $0301: staged sprite 0 Y coordinate
runtime_sprite_zero_pending_tile: .res 1 ; $0302: staged sprite 0 tile index
runtime_sprite_zero_pending_attributes: .res 1 ; $0303: staged sprite 0 attributes
runtime_sprite_zero_ready: .res 1 ; $0304: atomic sprite 0 staging commit flag
runtime_ppuctrl_shadow: .res 1 ; $0305: authoritative PPUCTRL value restored each NMI
runtime_ppumask_shadow: .res 1 ; $0306: authoritative PPUMASK value restored each NMI
runtime_scroll_x_shadow: .res 1 ; $0307: authoritative horizontal scroll restored each NMI
runtime_scroll_y_shadow: .res 1 ; $0308: authoritative vertical scroll restored each NMI

.segment "USER_VARIABLES"
; Source: non-promoted variables and all parameters in regular CPU RAM
    ; no user variables

.segment "CODE"

; Interrupt handlers
NMI:
    pha
    txa
    pha
    tya
    pha

    inc runtime_frame_counter ; volatile 8-bit counter, wraps modulo 256
    lda #$01
    sta runtime_frame_ready   ; advisory; frame counter is authoritative

    ; Runtime: commit the legacy helper's complete staged sprite 0
    lda runtime_sprite_zero_ready
    beq @skip_sprite_zero_commit
    lda #$00
    sta runtime_sprite_zero_ready
    lda runtime_sprite_zero_pending_y
    sta runtime_oam_shadow
    lda runtime_sprite_zero_pending_tile
    sta runtime_oam_shadow + 1
    lda runtime_sprite_zero_pending_attributes
    sta runtime_oam_shadow + 2
    lda runtime_sprite_zero_pending_x
    sta runtime_oam_shadow + 3
@skip_sprite_zero_commit:
    ; Runtime: upload the complete OAM shadow during VBlank
    lda #$00
    sta $2003               ; OAM address
    lda #>runtime_oam_shadow
    sta $4014               ; page-aligned OAM DMA

    ; Runtime: authoritative final PPU state after all VBlank work
    bit $2002               ; reset the shared PPU write latch
    lda runtime_ppuctrl_shadow
    sta $2000
    lda runtime_scroll_x_shadow
    sta $2005               ; scroll X (first write)
    lda runtime_scroll_y_shadow
    sta $2005               ; scroll Y (second write)
    lda runtime_ppumask_shadow
    sta $2001

    pla
    tay
    pla
    tax
    pla
    rti

IRQ:
    rti

; Source: implicit NES runtime initialization
RESET:
    sei
    cld
    ldx #$40
    stx $4017               ; disable frame counter IRQ
    ldx #$FF
    txs
    inx                     ; X = 0
    stx $2000               ; disable NMI
    stx $2001               ; disable rendering
    stx $4010               ; disable DMC IRQ
    bit $2002               ; clear the vblank latch

@wait_vblank_1:
    bit $2002
    bpl @wait_vblank_1

    txa
@clear_ram:
    sta $0000, x
    sta $0100, x
    sta $0200, x
    sta $0300, x
    sta $0400, x
    sta $0500, x
    sta $0600, x
    sta $0700, x
    inx
    bne @clear_ram

@wait_vblank_2:
    bit $2002
    bpl @wait_vblank_2

    ; Runtime: hide all 64 sprites before the first OAM DMA
    lda #$FF
    ldx #$00
@hide_all_sprites:
    sta runtime_oam_shadow, x
    inx
    inx
    inx
    inx
    bne @hide_all_sprites

; Source: PlayerX := value
    lda #$78
    sta variable_PlayerX

; Source: PlayerY := value
    lda #$70
    sta variable_PlayerY

; Source: PlayerTile := value
    lda #$01
    sta variable_PlayerTile

; Source: MovementSpeed := value
    lda #$01
    sta variable_MovementSpeed

; Source: WrapAtEdges := value
    lda #$00              ; false
    sta variable_WrapAtEdges

; Source: nes.set_sprite_zero(x, y, tile, attributes)
; Runtime: invalidate, stage all bytes, then publish atomically
    lda #$00
    sta runtime_sprite_zero_ready
    lda variable_PlayerX
    sta runtime_sprite_zero_pending_x
    lda variable_PlayerY
    sta runtime_sprite_zero_pending_y
    lda variable_PlayerTile
    sta runtime_sprite_zero_pending_tile
    lda #$00
    sta runtime_sprite_zero_pending_attributes
    lda #$01
    sta runtime_sprite_zero_ready

; Source: nes.set_background_color(value)
    lda #$3F
    sta $2006               ; universal palette address, high byte
    lda #$00
    sta $2006               ; low byte
    lda #$0F
    sta $2007

; Source: nes.on_update(Update)
; Runtime: static callback registration; no state emitted

; Source: nes.run
; Runtime: defer rendering-sensitive setup to VBlank
@wait_render_vblank_0:
    bit $2002
    bpl @wait_render_vblank_0
    ; Runtime: minimal palette for fixed sprite 0 support
    lda #$3F
    sta $2006
    lda #$11
    sta $2006
    lda #$16
    sta $2007
    lda #$27
    sta $2007
    lda #$30
    sta $2007
    lda runtime_ppuctrl_shadow
    ora #$80
    sta runtime_ppuctrl_shadow ; preserve bits and enable NMI
    sta $2000
    lda runtime_scroll_x_shadow ; zero-filled default scroll X
    sta $2005
    lda runtime_scroll_y_shadow ; zero-filled default scroll Y
    sta $2005
    lda runtime_ppumask_shadow
    ora #$1E
    sta runtime_ppumask_shadow ; preserve bits and enable rendering
    sta $2001

; Runtime: frame-synchronized update callback loop
    ; Establish the frame baseline once when the callback loop starts.
    lda runtime_frame_counter
    sta runtime_last_processed_frame
@runtime_update_loop:
    lda runtime_frame_counter
    cmp runtime_last_processed_frame
    beq @runtime_update_loop
    ; Accept only the newest pending frame; never replay a backlog.
    sta runtime_last_processed_frame
    lda #$00
    sta runtime_frame_ready ; advisory latch only; counter comparison is authoritative
    lda runtime_last_processed_frame
    jsr runtime_update_controllers ; exactly once for the accepted frame
    jsr procedure_Update
    jmp @runtime_update_loop

; Runtime: idempotent controller update for one newly processed frame
runtime_update_controllers:
    tax                     ; X keeps the caller's accepted frame value
    lda runtime_controller_poll_valid
    beq @controllers_need_poll
    txa
    cmp runtime_controller_polled_frame
    beq @controllers_already_current
@controllers_need_poll:
    lda #$01
    sta runtime_controller_poll_valid
    txa
    sta runtime_controller_polled_frame
    lda runtime_controller_1_current
    sta runtime_controller_1_previous
    lda runtime_controller_2_current
    sta runtime_controller_2_previous
    jsr runtime_read_controller_ports
@controllers_already_current:
    rts

; Runtime: isolated standard NES serial controller protocol
; Bit layout: A, B, Select, Start, Up, Down, Left, Right = bits 0..7.
runtime_read_controller_ports:
    lda #$01
    sta $4016               ; latch both controllers
    lda #$00
    sta $4016               ; begin serial reads
    sta runtime_controller_1_current
    sta runtime_controller_2_current
    ldx #$08
@read_controller_bits:
    lda $4016
    lsr a                   ; controller 1 serial bit -> carry
    ror runtime_controller_1_current
    lda $4017
    lsr a                   ; controller 2 serial bit -> carry
    ror runtime_controller_2_current
    dex
    bne @read_controller_bits
    rts


; Source: procedure declarations
; Procedure: Update
procedure_Update:

; Source: MovementSpeed := value
    lda #$01
    sta variable_MovementSpeed

; Source: if condition then
    ; nes.controller_down($01, nes.button_a): branch result
    lda runtime_controller_1_current
    and #$01
    bne @if_then_1
    jmp @if_end_2       ; long-branch-safe false path
@if_then_1:

; Source: MovementSpeed := value
    lda #$02
    sta variable_MovementSpeed
@if_end_2:

; Source: if condition then
    ; nes.controller_pressed($01, nes.button_select): branch result
    lda runtime_controller_1_current
    and #$04
    beq @controller_branch_false_5
    lda runtime_controller_1_previous
    and #$04
    beq @if_then_3
@controller_branch_false_5:
    jmp @if_end_4       ; long-branch-safe false path
@if_then_3:

; Source: WrapAtEdges := value
    ; boolean not
    lda variable_WrapAtEdges
    beq @not_true_6
    lda #$00              ; false
    jmp @not_end_7
@not_true_6:
    lda #$01              ; true
@not_end_7:
    sta variable_WrapAtEdges
@if_end_4:

; Source: if condition then
    ; nes.controller_down($01, nes.button_left): branch result
    lda runtime_controller_1_current
    and #$40
    bne @if_then_8
    jmp @if_end_9       ; long-branch-safe false path
@if_then_8:

; Source: if condition then
    ; comparison <=: direct right operand
    lda variable_PlayerX
    cmp #$0A
    bcc @if_then_10
    beq @if_then_10
    jmp @if_else_12       ; long-branch-safe false path
@if_then_10:

; Source: if condition then
    lda variable_WrapAtEdges
    bne @if_then_13
    jmp @if_else_15       ; long-branch-safe false path
@if_then_13:

; Source: PlayerX := value
    lda #$F7
    sta variable_PlayerX
    jmp @if_end_14
@if_else_15:

; Source: PlayerX := value
    lda #$08
    sta variable_PlayerX
@if_end_14:
    jmp @if_end_11
@if_else_12:

; Source: PlayerX := value
    ; binary -: direct right operand
    lda variable_PlayerX
    sec
    sbc variable_MovementSpeed
    sta variable_PlayerX
@if_end_11:
@if_end_9:

; Source: if condition then
    ; nes.controller_down($01, nes.button_right): branch result
    lda runtime_controller_1_current
    and #$80
    bne @if_then_16
    jmp @if_end_17       ; long-branch-safe false path
@if_then_16:

; Source: if condition then
    ; comparison >=: direct right operand
    lda variable_PlayerX
    cmp #$F5
    bcs @if_then_18
    jmp @if_else_20       ; long-branch-safe false path
@if_then_18:

; Source: if condition then
    lda variable_WrapAtEdges
    bne @if_then_21
    jmp @if_else_23       ; long-branch-safe false path
@if_then_21:

; Source: PlayerX := value
    lda #$08
    sta variable_PlayerX
    jmp @if_end_22
@if_else_23:

; Source: PlayerX := value
    lda #$F7
    sta variable_PlayerX
@if_end_22:
    jmp @if_end_19
@if_else_20:

; Source: PlayerX := value
    ; binary +: direct right operand
    lda variable_PlayerX
    clc
    adc variable_MovementSpeed
    sta variable_PlayerX
@if_end_19:
@if_end_17:

; Source: if condition then
    ; nes.controller_down($01, nes.button_up): branch result
    lda runtime_controller_1_current
    and #$10
    bne @if_then_24
    jmp @if_end_25       ; long-branch-safe false path
@if_then_24:

; Source: if condition then
    ; comparison <=: direct right operand
    lda variable_PlayerY
    cmp #$12
    bcc @if_then_26
    beq @if_then_26
    jmp @if_else_28       ; long-branch-safe false path
@if_then_26:

; Source: if condition then
    lda variable_WrapAtEdges
    bne @if_then_29
    jmp @if_else_31       ; long-branch-safe false path
@if_then_29:

; Source: PlayerY := value
    lda #$DF
    sta variable_PlayerY
    jmp @if_end_30
@if_else_31:

; Source: PlayerY := value
    lda #$10
    sta variable_PlayerY
@if_end_30:
    jmp @if_end_27
@if_else_28:

; Source: PlayerY := value
    ; binary -: direct right operand
    lda variable_PlayerY
    sec
    sbc variable_MovementSpeed
    sta variable_PlayerY
@if_end_27:
@if_end_25:

; Source: if condition then
    ; nes.controller_down($01, nes.button_down): branch result
    lda runtime_controller_1_current
    and #$20
    bne @if_then_32
    jmp @if_end_33       ; long-branch-safe false path
@if_then_32:

; Source: if condition then
    ; comparison >=: direct right operand
    lda variable_PlayerY
    cmp #$DD
    bcs @if_then_34
    jmp @if_else_36       ; long-branch-safe false path
@if_then_34:

; Source: if condition then
    lda variable_WrapAtEdges
    bne @if_then_37
    jmp @if_else_39       ; long-branch-safe false path
@if_then_37:

; Source: PlayerY := value
    lda #$10
    sta variable_PlayerY
    jmp @if_end_38
@if_else_39:

; Source: PlayerY := value
    lda #$DF
    sta variable_PlayerY
@if_end_38:
    jmp @if_end_35
@if_else_36:

; Source: PlayerY := value
    ; binary +: direct right operand
    lda variable_PlayerY
    clc
    adc variable_MovementSpeed
    sta variable_PlayerY
@if_end_35:
@if_end_33:

; Source: if condition then
    ; nes.controller_pressed($01, nes.button_b): branch result
    lda runtime_controller_1_current
    and #$02
    beq @controller_branch_false_42
    lda runtime_controller_1_previous
    and #$02
    beq @if_then_40
@controller_branch_false_42:
    jmp @if_end_41       ; long-branch-safe false path
@if_then_40:

; Source: PlayerTile := value
    lda #$02
    sta variable_PlayerTile
@if_end_41:

; Source: if condition then
    ; nes.controller_released($01, nes.button_b): branch result
    lda runtime_controller_1_current
    and #$02
    bne @controller_branch_false_45
    lda runtime_controller_1_previous
    and #$02
    bne @if_then_43
@controller_branch_false_45:
    jmp @if_end_44       ; long-branch-safe false path
@if_then_43:

; Source: PlayerTile := value
    lda #$01
    sta variable_PlayerTile
@if_end_44:

; Source: if condition then
    ; nes.controller_pressed($01, nes.button_start): branch result
    lda runtime_controller_1_current
    and #$08
    beq @controller_branch_false_48
    lda runtime_controller_1_previous
    and #$08
    beq @if_then_46
@controller_branch_false_48:
    jmp @if_end_47       ; long-branch-safe false path
@if_then_46:

; Source: PlayerX := value
    lda #$78
    sta variable_PlayerX

; Source: PlayerY := value
    lda #$70
    sta variable_PlayerY
@if_end_47:

; Source: nes.set_sprite_zero(x, y, tile, attributes)
; Runtime: invalidate, stage all bytes, then publish atomically
    lda #$00
    sta runtime_sprite_zero_ready
    lda variable_PlayerX
    sta runtime_sprite_zero_pending_x
    lda variable_PlayerY
    sta runtime_sprite_zero_pending_y
    lda variable_PlayerTile
    sta runtime_sprite_zero_pending_tile
    lda #$00
    sta runtime_sprite_zero_pending_attributes
    lda #$01
    sta runtime_sprite_zero_ready
    rts

.segment "VECTORS"
    .word NMI
    .word RESET
    .word IRQ

.segment "CHR"
    ; Runtime example asset: transparent tile 0 and two player tiles
    .res $0010, $00
    .byte $3C, $7E, $DB, $FF, $FF, $BD, $66, $3C ; tile 1 plane 0
    .byte $00, $24, $24, $00, $00, $42, $18, $00 ; tile 1 plane 1
    .byte $7E, $FF, $A5, $FF, $BD, $C3, $7E, $24 ; tile 2 plane 0
    .byte $00, $5A, $5A, $00, $42, $3C, $00, $18 ; tile 2 plane 1
    .res 8144, $00
