; Generated by nes-pascal for program Counting
; Mapper 0, 32 KiB PRG-ROM, 8 KiB CHR-ROM

.segment "HEADER"
    .byte "NES", $1A
    .byte 2                  ; PRG-ROM banks, 16 KiB each
    .byte 1                  ; CHR-ROM banks, 8 KiB each
    .byte $00                ; mapper and mirroring flags
    .byte $00                ; mapper upper bits
    .byte $00, $00, $00, $00, $00, $00, $00, $00

.segment "ZERO_PAGE_RUNTIME": zeropage
; Runtime: frame synchronization state, isolated from compiler temporaries
runtime_frame_counter: .res 1 ; $0000: volatile 8-bit counter incremented once by each NMI
runtime_frame_ready: .res 1 ; $0001: advisory frame-ready signal consumed by main frame waits
runtime_last_processed_frame: .res 1 ; $0002: persistent update-loop frame baseline
runtime_controller_1_current: .res 1 ; $0003: controller 1 state for the newest processed frame
runtime_controller_1_previous: .res 1 ; $0004: controller 1 state for the preceding processed frame
runtime_controller_2_current: .res 1 ; $0005: controller 2 state for the newest processed frame
runtime_controller_2_previous: .res 1 ; $0006: controller 2 state for the preceding processed frame
runtime_controller_polled_frame: .res 1 ; $0007: frame counter value of the most recent controller poll
runtime_controller_poll_valid: .res 1 ; $0008: distinguishes an initial zero byte from a completed frame-zero poll

.segment "ZERO_PAGE_TEMPORARIES": zeropage
; Compiler: mandatory expression and loop storage in Zero Page
expression_temporary_0: .res 1 ; $0010: reusable expression evaluation byte
for_limit_0: .res 1 ; $0011: cached for-loop final value
for_limit_1: .res 1 ; $0012: cached for-loop final value
for_limit_2: .res 1 ; $0013: cached for-loop final value
for_limit_3: .res 1 ; $0014: cached for-loop final value
for_limit_4: .res 1 ; $0015: cached for-loop final value
for_limit_5: .res 1 ; $0016: cached for-loop final value

.segment "ZERO_PAGE_VARIABLES": zeropage
; Source: optional global-variable promotion with regular-RAM fallback
variable_Counter: .res 1 ; $0080: Counter: byte
variable_Sum: .res 1 ; $0081: Sum: byte
variable_BackgroundColor: .res 1 ; $0082: BackgroundColor: nes_color


.segment "RUNTIME_DATA"
; Runtime: regular-RAM state kept separate from user variables
    ; no scalar regular-RAM runtime symbols required

.segment "USER_VARIABLES"
; Source: non-promoted variables and all parameters in regular CPU RAM
variable_Index: .res 1 ; $0200: Index: byte
variable_Reverse: .res 1 ; $0201: Reverse: byte
variable_Edge: .res 1 ; $0202: Edge: byte
variable_Outer: .res 1 ; $0203: Outer: byte
variable_Inner: .res 1 ; $0204: Inner: byte

.segment "CODE"

; Interrupt handlers
NMI:
    pha
    txa
    pha
    tya
    pha

    inc runtime_frame_counter ; volatile 8-bit counter, wraps modulo 256
    lda #$01
    sta runtime_frame_ready   ; advisory; frame counter is authoritative

    pla
    tay
    pla
    tax
    pla
    rti

IRQ:
    rti

; Source: implicit NES runtime initialization
RESET:
    sei
    cld
    ldx #$40
    stx $4017               ; disable frame counter IRQ
    ldx #$FF
    txs
    inx                     ; X = 0
    stx $2000               ; disable NMI
    stx $2001               ; disable rendering
    stx $4010               ; disable DMC IRQ
    bit $2002               ; clear the vblank latch

@wait_vblank_1:
    bit $2002
    bpl @wait_vblank_1

    txa
@clear_ram:
    sta $0000, x
    sta $0100, x
    sta $0200, x
    sta $0300, x
    sta $0400, x
    sta $0500, x
    sta $0600, x
    sta $0700, x
    inx
    bne @clear_ram

@wait_vblank_2:
    bit $2002
    bpl @wait_vblank_2

; Source: Counter := value
    lda #$FE
    sta variable_Counter

; Source: inc(Counter)
    inc variable_Counter

; Source: inc(Counter)
    inc variable_Counter

; Source: dec(Counter)
    dec variable_Counter

; Source: dec(Counter, amount)
    lda #$02
    sta expression_temporary_0
    lda variable_Counter
    sec
    sbc expression_temporary_0
    sta variable_Counter

; Source: Sum := value
    lda #$00
    sta variable_Sum

; Source: for variable := initial to final do
    lda #$00
    sta variable_Index
    lda #$03
    sta for_limit_0   ; evaluate final value once
@for_condition_0:
    lda variable_Index
    cmp for_limit_0
    bcc @for_body_1
    beq @for_body_1
    jmp @for_end_3       ; long-branch-safe loop exit
@for_body_1:

; Source: inc(Sum)
    inc variable_Sum
@for_step_2:
    lda variable_Index
    cmp for_limit_0
    beq @for_end_3        ; stop before byte wraparound
    inc variable_Index
    jmp @for_condition_0
@for_end_3:

; Source: for variable := initial downto final do
    lda #$02
    sta variable_Reverse
    lda #$00
    sta for_limit_1   ; evaluate final value once
@for_condition_4:
    lda variable_Reverse
    cmp for_limit_1
    bcs @for_body_5
    jmp @for_end_7       ; long-branch-safe loop exit
@for_body_5:

; Source: inc(Sum, amount)
    lda #$02
    clc
    adc variable_Sum
    sta variable_Sum
@for_step_6:
    lda variable_Reverse
    cmp for_limit_1
    beq @for_end_7        ; stop before byte wraparound
    dec variable_Reverse
    jmp @for_condition_4
@for_end_7:

; Source: for variable := initial to final do
    lda #$FF
    sta variable_Edge
    lda #$FF
    sta for_limit_2   ; evaluate final value once
@for_condition_8:
    lda variable_Edge
    cmp for_limit_2
    bcc @for_body_9
    beq @for_body_9
    jmp @for_end_11       ; long-branch-safe loop exit
@for_body_9:

; Source: inc(Sum)
    inc variable_Sum
@for_step_10:
    lda variable_Edge
    cmp for_limit_2
    beq @for_end_11        ; stop before byte wraparound
    inc variable_Edge
    jmp @for_condition_8
@for_end_11:

; Source: for variable := initial downto final do
    lda #$00
    sta variable_Edge
    lda #$00
    sta for_limit_3   ; evaluate final value once
@for_condition_12:
    lda variable_Edge
    cmp for_limit_3
    bcs @for_body_13
    jmp @for_end_15       ; long-branch-safe loop exit
@for_body_13:

; Source: inc(Sum)
    inc variable_Sum
@for_step_14:
    lda variable_Edge
    cmp for_limit_3
    beq @for_end_15        ; stop before byte wraparound
    dec variable_Edge
    jmp @for_condition_12
@for_end_15:

; Source: for variable := initial to final do
    lda #$00
    sta variable_Outer
    lda #$01
    sta for_limit_4   ; evaluate final value once
@for_condition_16:
    lda variable_Outer
    cmp for_limit_4
    bcc @for_body_17
    beq @for_body_17
    jmp @for_end_19       ; long-branch-safe loop exit
@for_body_17:

; Source: for variable := initial to final do
    lda #$00
    sta variable_Inner
    lda #$01
    sta for_limit_5   ; evaluate final value once
@for_condition_20:
    lda variable_Inner
    cmp for_limit_5
    bcc @for_body_21
    beq @for_body_21
    jmp @for_end_23       ; long-branch-safe loop exit
@for_body_21:

; Source: inc(Sum)
    inc variable_Sum
@for_step_22:
    lda variable_Inner
    cmp for_limit_5
    beq @for_end_23        ; stop before byte wraparound
    inc variable_Inner
    jmp @for_condition_20
@for_end_23:
@for_step_18:
    lda variable_Outer
    cmp for_limit_4
    beq @for_end_19        ; stop before byte wraparound
    inc variable_Outer
    jmp @for_condition_16
@for_end_19:

; Source: if condition then
    ; boolean and: evaluate left operand
    ; comparison =: evaluate right operand
    lda #$FD
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    beq @comparison_true_31
@comparison_false_32:
    lda #$00              ; false
    jmp @comparison_end_33
@comparison_true_31:
    lda #$01              ; true
@comparison_end_33:
    cmp #$00
    bne @boolean_evaluate_right_27
    jmp @boolean_false_29       ; short-circuit false
@boolean_evaluate_right_27:
    ; evaluate right operand
    ; comparison =: evaluate right operand
    lda #$10
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Sum
    cmp expression_temporary_0
    beq @comparison_true_34
@comparison_false_35:
    lda #$00              ; false
    jmp @comparison_end_36
@comparison_true_34:
    lda #$01              ; true
@comparison_end_36:
    cmp #$00
    bne @boolean_true_28
@boolean_false_29:
    lda #$00              ; false
    jmp @boolean_end_30
@boolean_true_28:
    lda #$01              ; true
@boolean_end_30:
    cmp #$00
    bne @if_then_24
    jmp @if_else_26       ; long-branch-safe false path
@if_then_24:

; Source: BackgroundColor := value
    lda #$21
    sta variable_BackgroundColor
    jmp @if_end_25
@if_else_26:

; Source: BackgroundColor := value
    lda #$0F
    sta variable_BackgroundColor
@if_end_25:

; Source: nes.set_background_color(value)
    lda #$3F
    sta $2006               ; universal palette address, high byte
    lda #$00
    sta $2006               ; low byte
    lda variable_BackgroundColor
    sta $2007

; Source: nes.run
; Runtime: defer rendering-sensitive setup to VBlank
@wait_render_vblank_37:
    bit $2002
    bpl @wait_render_vblank_37
    lda #$00
    sta $2005               ; scroll X
    sta $2005               ; scroll Y
    lda #$80
    sta $2000               ; enable NMI after initialization
    lda #$08
    sta $2001               ; enable selected rendering layers

; Runtime: implicit stable loop after the main program finishes
@runtime_idle_loop:
    jmp @runtime_idle_loop

; Runtime: idempotent controller update for one newly processed frame
runtime_update_controllers:
    tax                     ; X keeps the caller's accepted frame value
    lda runtime_controller_poll_valid
    beq @controllers_need_poll
    txa
    cmp runtime_controller_polled_frame
    beq @controllers_already_current
@controllers_need_poll:
    lda #$01
    sta runtime_controller_poll_valid
    txa
    sta runtime_controller_polled_frame
    lda runtime_controller_1_current
    sta runtime_controller_1_previous
    lda runtime_controller_2_current
    sta runtime_controller_2_previous
    jsr runtime_read_controller_ports
@controllers_already_current:
    rts

; Runtime: isolated standard NES serial controller protocol
; Bit layout: A, B, Select, Start, Up, Down, Left, Right = bits 0..7.
runtime_read_controller_ports:
    lda #$01
    sta $4016               ; latch both controllers
    lda #$00
    sta $4016               ; begin serial reads
    sta runtime_controller_1_current
    sta runtime_controller_2_current
    ldx #$08
@read_controller_bits:
    lda $4016
    lsr a                   ; controller 1 serial bit -> carry
    ror runtime_controller_1_current
    lda $4017
    lsr a                   ; controller 2 serial bit -> carry
    ror runtime_controller_2_current
    dex
    bne @read_controller_bits
    rts


.segment "VECTORS"
    .word NMI
    .word RESET
    .word IRQ

.segment "CHR"
    .res 8192, $00          ; empty CHR-ROM
