; Generated by nes-pascal for program Loops
; Mapper 0, 32 KiB PRG-ROM, 8 KiB CHR-ROM

.segment "HEADER"
    .byte "NES", $1A
    .byte 2                  ; PRG-ROM banks, 16 KiB each
    .byte 1                  ; CHR-ROM banks, 8 KiB each
    .byte $00                ; mapper and mirroring flags
    .byte $00                ; mapper upper bits
    .byte $00, $00, $00, $00, $00, $00, $00, $00

.segment "ZERO_PAGE_RUNTIME": zeropage
; Runtime: frame synchronization state, isolated from compiler temporaries
runtime_frame_counter: .res 1 ; $0000: volatile 8-bit counter incremented once by each NMI
runtime_frame_ready: .res 1 ; $0001: advisory frame-ready signal consumed by main frame waits
runtime_last_processed_frame: .res 1 ; $0002: persistent update-loop frame baseline

.segment "ZERO_PAGE_TEMPORARIES": zeropage
; Compiler: mandatory expression and loop storage in Zero Page
expression_temporary_0: .res 1 ; $0010: reusable expression evaluation byte

.segment "ZERO_PAGE_VARIABLES": zeropage
; Source: optional global-variable promotion with regular-RAM fallback
variable_Counter: .res 1 ; $0080: Counter: byte
variable_InnerCounter: .res 1 ; $0081: InnerCounter: byte
variable_BackgroundColor: .res 1 ; $0082: BackgroundColor: nes_color

.segment "OAM_SHADOW"
; Runtime: page-aligned OAM DMA shadow at $0200-$02FF
runtime_oam_shadow: .res 256 ; $0200: 256-byte page copied to PPU OAM by future sprite runtime support

.segment "RUNTIME_DATA"
; Runtime: no scalar regular-RAM symbols are currently required

.segment "USER_VARIABLES"
; Source: non-promoted variables and all parameters in regular CPU RAM
    ; no user variables

.segment "CODE"

; Interrupt handlers
NMI:
    pha
    txa
    pha
    tya
    pha

    inc runtime_frame_counter ; volatile 8-bit counter, wraps modulo 256
    lda #$01
    sta runtime_frame_ready   ; advisory; frame counter is authoritative

    pla
    tay
    pla
    tax
    pla
    rti

IRQ:
    rti

; Source: implicit NES runtime initialization
RESET:
    sei
    cld
    ldx #$40
    stx $4017               ; disable frame counter IRQ
    ldx #$FF
    txs
    inx                     ; X = 0
    stx $2000               ; disable NMI
    stx $2001               ; disable rendering
    stx $4010               ; disable DMC IRQ
    bit $2002               ; clear the vblank latch

@wait_vblank_1:
    bit $2002
    bpl @wait_vblank_1

    txa
@clear_ram:
    sta $0000, x
    sta $0100, x
    sta $0200, x
    sta $0300, x
    sta $0400, x
    sta $0500, x
    sta $0600, x
    sta $0700, x
    inx
    bne @clear_ram

@wait_vblank_2:
    bit $2002
    bpl @wait_vblank_2

; Source: Counter := value
    lda #$00
    sta variable_Counter

; Source: InnerCounter := value
    lda #$00
    sta variable_InnerCounter

; Source: while condition do
@while_condition_0:
    ; comparison <: evaluate right operand
    lda #$06
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    bcc @comparison_true_3
@comparison_false_4:
    lda #$00              ; false
    jmp @comparison_end_5
@comparison_true_3:
    lda #$01              ; true
@comparison_end_5:
    cmp #$00
    bne @while_body_1
    jmp @while_end_2       ; long-branch-safe loop exit
@while_body_1:

; Source: Counter := value
    ; binary +: evaluate right operand
    lda #$01
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    clc
    adc expression_temporary_0
    sta variable_Counter

; Source: if condition then
    ; comparison =: evaluate right operand
    lda #$02
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    beq @comparison_true_8
@comparison_false_9:
    lda #$00              ; false
    jmp @comparison_end_10
@comparison_true_8:
    lda #$01              ; true
@comparison_end_10:
    cmp #$00
    bne @if_then_6
    jmp @if_end_7       ; long-branch-safe false path
@if_then_6:

; Source: continue
    jmp @while_condition_0
@if_end_7:

; Source: if condition then
    ; comparison =: evaluate right operand
    lda #$05
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    beq @comparison_true_13
@comparison_false_14:
    lda #$00              ; false
    jmp @comparison_end_15
@comparison_true_13:
    lda #$01              ; true
@comparison_end_15:
    cmp #$00
    bne @if_then_11
    jmp @if_end_12       ; long-branch-safe false path
@if_then_11:

; Source: break
    jmp @while_end_2
@if_end_12:

; Source: InnerCounter := value
    ; binary +: evaluate right operand
    lda #$01
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_InnerCounter
    clc
    adc expression_temporary_0
    sta variable_InnerCounter
    jmp @while_condition_0
@while_end_2:

; Source: repeat until condition
@repeat_body_16:

; Source: InnerCounter := value
    ; binary -: evaluate right operand
    lda #$01
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_InnerCounter
    sec
    sbc expression_temporary_0
    sta variable_InnerCounter
@repeat_condition_17:
    ; comparison =: evaluate right operand
    lda #$00
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_InnerCounter
    cmp expression_temporary_0
    beq @comparison_true_19
@comparison_false_20:
    lda #$00              ; false
    jmp @comparison_end_21
@comparison_true_19:
    lda #$01              ; true
@comparison_end_21:
    cmp #$00
    bne @repeat_end_18
    jmp @repeat_body_16       ; long-branch-safe repeat
@repeat_end_18:

; Source: if condition then
    ; comparison =: evaluate right operand
    lda #$05
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    beq @comparison_true_25
@comparison_false_26:
    lda #$00              ; false
    jmp @comparison_end_27
@comparison_true_25:
    lda #$01              ; true
@comparison_end_27:
    cmp #$00
    bne @if_then_22
    jmp @if_else_24       ; long-branch-safe false path
@if_then_22:

; Source: BackgroundColor := value
    lda #$21
    sta variable_BackgroundColor
    jmp @if_end_23
@if_else_24:

; Source: BackgroundColor := value
    lda #$0F
    sta variable_BackgroundColor
@if_end_23:

; Source: nes.set_background_color(value)
    lda #$3F
    sta $2006               ; universal palette address, high byte
    lda #$00
    sta $2006               ; low byte
    lda variable_BackgroundColor
    sta $2007

; Source: nes.run
; Runtime: defer rendering-sensitive setup to VBlank
@wait_render_vblank_28:
    bit $2002
    bpl @wait_render_vblank_28
    lda #$00
    sta $2005               ; scroll X
    sta $2005               ; scroll Y
    lda #$80
    sta $2000               ; enable NMI after initialization
    lda #$08
    sta $2001               ; enable background rendering

; Runtime: implicit stable loop after the main program finishes
@runtime_idle_loop:
    jmp @runtime_idle_loop


.segment "VECTORS"
    .word NMI
    .word RESET
    .word IRQ

.segment "CHR"
    .res 8192, $00          ; empty CHR-ROM
