; Generated by nes-pascal for program LowRiskCodegen
; Mapper 0, 32 KiB PRG-ROM, 8 KiB CHR-ROM

.segment "HEADER"
    .byte "NES", $1A
    .byte 2                  ; PRG-ROM banks, 16 KiB each
    .byte 1                  ; CHR-ROM banks, 8 KiB each
    .byte $00                ; mapper and mirroring flags
    .byte $00                ; mapper upper bits
    .byte $00, $00, $00, $00, $00, $00, $00, $00

.segment "ZERO_PAGE_RUNTIME": zeropage
; Runtime: frame synchronization state, isolated from compiler temporaries
runtime_frame_counter: .res 1 ; $0000: volatile 8-bit counter incremented once by each NMI
runtime_frame_ready: .res 1 ; $0001: advisory frame-ready signal consumed by main frame waits
runtime_last_processed_frame: .res 1 ; $0002: persistent update-loop frame baseline
runtime_controller_1_current: .res 1 ; $0003: controller 1 state for the newest processed frame
runtime_controller_1_previous: .res 1 ; $0004: controller 1 state for the preceding processed frame
runtime_controller_2_current: .res 1 ; $0005: controller 2 state for the newest processed frame
runtime_controller_2_previous: .res 1 ; $0006: controller 2 state for the preceding processed frame
runtime_controller_polled_frame: .res 1 ; $0007: frame counter value of the most recent controller poll
runtime_controller_poll_valid: .res 1 ; $0008: distinguishes an initial zero byte from a completed frame-zero poll

.segment "ZERO_PAGE_TEMPORARIES": zeropage
; Compiler: mandatory expression and loop storage in Zero Page
    ; no compiler temporaries required

.segment "ZERO_PAGE_VARIABLES": zeropage
; Source: optional global-variable promotion with regular-RAM fallback
variable_Left: .res 1 ; $0080: Left: byte
variable_Right: .res 1 ; $0081: Right: byte
variable_Result: .res 1 ; $0082: Result: byte
variable_Other: .res 1 ; $0083: Other: boolean


.segment "RUNTIME_DATA"
; Runtime: regular-RAM state kept separate from user variables
runtime_ppuctrl_shadow: .res 1 ; $0200: authoritative PPUCTRL value restored each NMI
runtime_ppumask_shadow: .res 1 ; $0201: authoritative PPUMASK value restored each NMI
runtime_scroll_x_shadow: .res 1 ; $0202: authoritative horizontal scroll restored each NMI
runtime_scroll_y_shadow: .res 1 ; $0203: authoritative vertical scroll restored each NMI

.segment "USER_VARIABLES"
; Source: non-promoted variables and all parameters in regular CPU RAM
variable_Stored: .res 1 ; $0204: Stored: boolean

.segment "CODE"

; Interrupt handlers
NMI:
    pha
    txa
    pha
    tya
    pha

    inc runtime_frame_counter ; volatile 8-bit counter, wraps modulo 256
    lda #$01
    sta runtime_frame_ready   ; advisory; frame counter is authoritative

    ; Runtime: authoritative final PPU state after all VBlank work
    bit $2002               ; reset the shared PPU write latch
    lda runtime_ppuctrl_shadow
    sta $2000
    lda runtime_scroll_x_shadow
    sta $2005               ; scroll X (first write)
    lda runtime_scroll_y_shadow
    sta $2005               ; scroll Y (second write)
    lda runtime_ppumask_shadow
    sta $2001

    pla
    tay
    pla
    tax
    pla
    rti

IRQ:
    rti

; Source: implicit NES runtime initialization
RESET:
    sei
    cld
    ldx #$40
    stx $4017               ; disable frame counter IRQ
    ldx #$FF
    txs
    inx                     ; X = 0
    stx $2000               ; disable NMI
    stx $2001               ; disable rendering
    stx $4010               ; disable DMC IRQ
    bit $2002               ; clear the vblank latch

@wait_vblank_1:
    bit $2002
    bpl @wait_vblank_1

    txa
@clear_ram:
    sta $0000, x
    sta $0100, x
    sta $0200, x
    sta $0300, x
    sta $0400, x
    sta $0500, x
    sta $0600, x
    sta $0700, x
    inx
    bne @clear_ram

@wait_vblank_2:
    bit $2002
    bpl @wait_vblank_2

; Source: Left := value
    lda #$02
    sta variable_Left

; Source: Right := value
    lda #$03
    sta variable_Right

; Source: Result := value
    ; binary +: direct right operand
    lda variable_Left
    clc
    adc #$01
    sta variable_Result

; Source: Result := value
    ; binary -: direct right operand
    lda variable_Result
    sec
    sbc variable_Right
    sta variable_Result

; Source: Stored := value
    ; comparison <: direct right operand
    lda variable_Left
    cmp #$08
    bcc @comparison_true_0
@comparison_false_1:
    lda #$00              ; false
    jmp @comparison_end_2
@comparison_true_0:
    lda #$01              ; true
@comparison_end_2:
    sta variable_Stored

; Source: Other := value
    ; comparison <>: direct right operand
    lda variable_Left
    cmp variable_Right
    bne @comparison_true_3
@comparison_false_4:
    lda #$00              ; false
    jmp @comparison_end_5
@comparison_true_3:
    lda #$01              ; true
@comparison_end_5:
    sta variable_Other

; Source: if condition then
    ; boolean and: branch left operand
    ; comparison <: direct right operand
    lda variable_Left
    cmp variable_Right
    bcc @boolean_branch_right_8
    jmp @if_end_7       ; long-branch-safe false path
@boolean_branch_right_8:
    ; boolean and: branch right operand
    ; boolean not: branch result
    lda variable_Other
    bne @not_branch_operand_true_9
    jmp @if_then_6
@not_branch_operand_true_9:
    jmp @if_end_7       ; long-branch-safe false path
@if_then_6:

; Source: Result := value
    ; binary +: direct right operand
    lda variable_Result
    clc
    adc #$01
    sta variable_Result
@if_end_7:

; Source: if condition then
    ; boolean or: branch left operand
    lda variable_Stored
    bne @boolean_branch_true_13
    jmp @boolean_branch_right_12
@boolean_branch_true_13:
    jmp @if_then_10       ; short-circuit true
@boolean_branch_right_12:
    ; boolean or: branch right operand
    lda variable_Other
    bne @if_then_10
    jmp @if_end_11       ; long-branch-safe false path
@if_then_10:

; Source: Result := value
    ; binary +: direct right operand
    lda variable_Result
    clc
    adc variable_Right
    sta variable_Result
@if_end_11:

; Source: while condition do
@while_condition_14:
    ; comparison <>: direct right operand
    lda variable_Left
    cmp #$04
    bne @while_body_15
    jmp @while_end_16       ; long-branch-safe loop exit
@while_body_15:

; Source: Left := value
    ; binary +: direct right operand
    lda variable_Left
    clc
    adc #$01
    sta variable_Left
    jmp @while_condition_14
@while_end_16:

; Source: repeat until condition
@repeat_body_17:

; Source: Right := value
    ; binary -: direct right operand
    lda variable_Right
    sec
    sbc #$01
    sta variable_Right
@repeat_condition_18:
    ; comparison =: direct right operand
    lda variable_Right
    cmp #$00
    beq @repeat_end_19
    jmp @repeat_body_17       ; long-branch-safe repeat
@repeat_end_19:

; Source: nes.set_background_color(value)
    lda #$3F
    sta $2006               ; universal palette address, high byte
    lda #$00
    sta $2006               ; low byte
    lda #$0F
    sta $2007

; Source: nes.run
; Runtime: defer rendering-sensitive setup to VBlank
@wait_render_vblank_20:
    bit $2002
    bpl @wait_render_vblank_20
    lda runtime_ppuctrl_shadow
    ora #$80
    sta runtime_ppuctrl_shadow ; preserve bits and enable NMI
    sta $2000
    lda runtime_scroll_x_shadow ; zero-filled default scroll X
    sta $2005
    lda runtime_scroll_y_shadow ; zero-filled default scroll Y
    sta $2005
    lda runtime_ppumask_shadow
    ora #$1E
    sta runtime_ppumask_shadow ; preserve bits and enable rendering
    sta $2001

; Runtime: implicit stable loop after the main program finishes
@runtime_idle_loop:
    jmp @runtime_idle_loop

; Runtime: idempotent controller update for one newly processed frame
runtime_update_controllers:
    tax                     ; X keeps the caller's accepted frame value
    lda runtime_controller_poll_valid
    beq @controllers_need_poll
    txa
    cmp runtime_controller_polled_frame
    beq @controllers_already_current
@controllers_need_poll:
    lda #$01
    sta runtime_controller_poll_valid
    txa
    sta runtime_controller_polled_frame
    lda runtime_controller_1_current
    sta runtime_controller_1_previous
    lda runtime_controller_2_current
    sta runtime_controller_2_previous
    jsr runtime_read_controller_ports
@controllers_already_current:
    rts

; Runtime: isolated standard NES serial controller protocol
; Bit layout: A, B, Select, Start, Up, Down, Left, Right = bits 0..7.
runtime_read_controller_ports:
    lda #$01
    sta $4016               ; latch both controllers
    lda #$00
    sta $4016               ; begin serial reads
    sta runtime_controller_1_current
    sta runtime_controller_2_current
    ldx #$08
@read_controller_bits:
    lda $4016
    lsr a                   ; controller 1 serial bit -> carry
    ror runtime_controller_1_current
    lda $4017
    lsr a                   ; controller 2 serial bit -> carry
    ror runtime_controller_2_current
    dex
    bne @read_controller_bits
    rts


.segment "VECTORS"
    .word NMI
    .word RESET
    .word IRQ

.segment "CHR"
    .res 8192, $00          ; empty CHR-ROM
