; Generated by nes-pascal for program MemoryLayout
; Mapper 0, 32 KiB PRG-ROM, 8 KiB CHR-ROM

.segment "HEADER"
    .byte "NES", $1A
    .byte 2                  ; PRG-ROM banks, 16 KiB each
    .byte 1                  ; CHR-ROM banks, 8 KiB each
    .byte $00                ; mapper and mirroring flags
    .byte $00                ; mapper upper bits
    .byte $00, $00, $00, $00, $00, $00, $00, $00

.segment "ZERO_PAGE_RUNTIME": zeropage
; Runtime: frame synchronization state, isolated from compiler temporaries
runtime_frame_counter: .res 1 ; $0000: volatile 8-bit counter incremented once by each NMI
runtime_frame_ready: .res 1 ; $0001: advisory frame-ready signal consumed by main frame waits
runtime_last_processed_frame: .res 1 ; $0002: persistent update-loop frame baseline

.segment "ZERO_PAGE_TEMPORARIES": zeropage
; Compiler: mandatory expression and loop storage in Zero Page
expression_temporary_0: .res 1 ; $0010: reusable expression evaluation byte
for_limit_0: .res 1 ; $0011: cached for-loop final value

.segment "ZERO_PAGE_VARIABLES": zeropage
; Source: optional global-variable promotion with regular-RAM fallback
variable_BackgroundColor: .res 1 ; $0080: BackgroundColor: nes_color
variable_FrameCounter: .res 1 ; $0081: FrameCounter: byte
variable_NextFrameCounter: .res 1 ; $0082: NextFrameCounter: byte

.segment "OAM_SHADOW"
; Runtime: page-aligned OAM DMA shadow at $0200-$02FF
runtime_oam_shadow: .res 256 ; $0200: 256-byte page copied to PPU OAM by future sprite runtime support

.segment "RUNTIME_DATA"
; Runtime: no scalar regular-RAM symbols are currently required

.segment "USER_VARIABLES"
; Source: non-promoted variables and all parameters in regular CPU RAM
variable_RenderingEnabled: .res 1 ; $0300: RenderingEnabled: boolean
variable_ExpectedState: .res 1 ; $0301: ExpectedState: boolean
parameter_InitializeCounters_Start: .res 1 ; $0302: InitializeCounters.Start: byte
parameter_InitializeCounters_Increment: .res 1 ; $0303: InitializeCounters.Increment: byte
parameter_InitializeCounters_EnabledValue: .res 1 ; $0304: InitializeCounters.EnabledValue: boolean

.segment "CODE"

; Interrupt handlers
NMI:
    pha
    txa
    pha
    tya
    pha

    inc runtime_frame_counter ; volatile 8-bit counter, wraps modulo 256
    lda #$01
    sta runtime_frame_ready   ; advisory; frame counter is authoritative

    pla
    tay
    pla
    tax
    pla
    rti

IRQ:
    rti

; Source: implicit NES runtime initialization
RESET:
    sei
    cld
    ldx #$40
    stx $4017               ; disable frame counter IRQ
    ldx #$FF
    txs
    inx                     ; X = 0
    stx $2000               ; disable NMI
    stx $2001               ; disable rendering
    stx $4010               ; disable DMC IRQ
    bit $2002               ; clear the vblank latch

@wait_vblank_1:
    bit $2002
    bpl @wait_vblank_1

    txa
@clear_ram:
    sta $0000, x
    sta $0100, x
    sta $0200, x
    sta $0300, x
    sta $0400, x
    sta $0500, x
    sta $0600, x
    sta $0700, x
    inx
    bne @clear_ram

@wait_vblank_2:
    bit $2002
    bpl @wait_vblank_2

; Source: BackgroundColor := value
    lda #$21
    sta variable_BackgroundColor

; Source: InitializeCounters
    ; argument 1: Start
    lda #$00
    sta parameter_InitializeCounters_Start
    ; argument 2: Increment
    lda #$01
    sta parameter_InitializeCounters_Increment
    ; argument 3: EnabledValue
    lda #$01              ; true
    sta parameter_InitializeCounters_EnabledValue
    jsr procedure_InitializeCounters

; Source: inc(NextFrameCounter)
    inc variable_NextFrameCounter

; Source: for variable := initial to final do
    lda #$00
    sta variable_FrameCounter
    lda #$03
    sta for_limit_0   ; evaluate final value once
@for_condition_0:
    lda variable_FrameCounter
    cmp for_limit_0
    bcc @for_body_1
    beq @for_body_1
    jmp @for_end_3       ; long-branch-safe loop exit
@for_body_1:

; Source: inc(NextFrameCounter)
    inc variable_NextFrameCounter
@for_step_2:
    lda variable_FrameCounter
    cmp for_limit_0
    beq @for_end_3        ; stop before byte wraparound
    inc variable_FrameCounter
    jmp @for_condition_0
@for_end_3:

; Source: ExpectedState := value
    ; boolean and: evaluate left operand
    lda variable_RenderingEnabled
    cmp #$00
    bne @boolean_evaluate_right_4
    jmp @boolean_false_6       ; short-circuit false
@boolean_evaluate_right_4:
    ; evaluate right operand
    ; comparison >: evaluate right operand
    lda #$03
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_NextFrameCounter
    cmp expression_temporary_0
    beq @comparison_false_9
    bcs @comparison_true_8
@comparison_false_9:
    lda #$00              ; false
    jmp @comparison_end_10
@comparison_true_8:
    lda #$01              ; true
@comparison_end_10:
    cmp #$00
    bne @boolean_true_5
@boolean_false_6:
    lda #$00              ; false
    jmp @boolean_end_7
@boolean_true_5:
    lda #$01              ; true
@boolean_end_7:
    sta variable_ExpectedState

; Source: if condition then
    lda variable_ExpectedState
    cmp #$00
    bne @if_then_11
    jmp @if_else_13       ; long-branch-safe false path
@if_then_11:

; Source: BackgroundColor := value
    lda #$21
    sta variable_BackgroundColor
    jmp @if_end_12
@if_else_13:

; Source: BackgroundColor := value
    lda #$0F
    sta variable_BackgroundColor
@if_end_12:

; Source: nes.set_background_color(value)
    lda #$3F
    sta $2006               ; universal palette address, high byte
    lda #$00
    sta $2006               ; low byte
    lda variable_BackgroundColor
    sta $2007

; Source: nes.run
; Runtime: defer rendering-sensitive setup to VBlank
@wait_render_vblank_14:
    bit $2002
    bpl @wait_render_vblank_14
    lda #$00
    sta $2005               ; scroll X
    sta $2005               ; scroll Y
    lda #$80
    sta $2000               ; enable NMI after initialization
    lda #$08
    sta $2001               ; enable background rendering

; Runtime: implicit stable loop after the main program finishes
@runtime_idle_loop:
    jmp @runtime_idle_loop


; Source: procedure declarations
; Procedure: InitializeCounters
procedure_InitializeCounters:

; Source: FrameCounter := value
    lda parameter_InitializeCounters_Start
    sta variable_FrameCounter

; Source: NextFrameCounter := value
    ; binary +: evaluate right operand
    lda parameter_InitializeCounters_Increment
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_FrameCounter
    clc
    adc expression_temporary_0
    sta variable_NextFrameCounter

; Source: RenderingEnabled := value
    lda parameter_InitializeCounters_EnabledValue
    sta variable_RenderingEnabled
    rts

.segment "VECTORS"
    .word NMI
    .word RESET
    .word IRQ

.segment "CHR"
    .res 8192, $00          ; empty CHR-ROM
