; Generated by nes-pascal for program MetaspritePlayer
; Mapper 0, 32 KiB PRG-ROM, 8 KiB CHR-ROM

.segment "HEADER"
    .byte "NES", $1A
    .byte 2                  ; PRG-ROM banks, 16 KiB each
    .byte 1                  ; CHR-ROM banks, 8 KiB each
    .byte $00                ; mapper and mirroring flags
    .byte $00                ; mapper upper bits
    .byte $00, $00, $00, $00, $00, $00, $00, $00

.segment "ZERO_PAGE_RUNTIME": zeropage
; Runtime: frame synchronization state, isolated from compiler temporaries
runtime_frame_counter: .res 1 ; $0000: volatile 8-bit counter incremented once by each NMI
runtime_frame_ready: .res 1 ; $0001: advisory frame-ready signal consumed by main frame waits
runtime_last_processed_frame: .res 1 ; $0002: persistent update-loop frame baseline
runtime_controller_1_current: .res 1 ; $0003: controller 1 state for the newest processed frame
runtime_controller_1_previous: .res 1 ; $0004: controller 1 state for the preceding processed frame
runtime_controller_2_current: .res 1 ; $0005: controller 2 state for the newest processed frame
runtime_controller_2_previous: .res 1 ; $0006: controller 2 state for the preceding processed frame
runtime_controller_polled_frame: .res 1 ; $0007: frame counter value of the most recent controller poll
runtime_controller_poll_valid: .res 1 ; $0008: distinguishes an initial zero byte from a completed frame-zero poll
runtime_metasprite_frame_pointer: .res 2 ; $0009: indirect pointer into immutable metasprite frame data
runtime_metasprite_slot_pointer: .res 2 ; $000B: indirect pointer into one metasprite OAM ownership table

.segment "ZERO_PAGE_TEMPORARIES": zeropage
; Compiler: mandatory expression and loop storage in Zero Page
    ; no compiler temporaries required

.segment "ZERO_PAGE_VARIABLES": zeropage
; Source: optional global-variable promotion with regular-RAM fallback
variable_Player: .res 1 ; $0080: Player: metasprite
variable_PlayerX: .res 1 ; $0081: PlayerX: byte
variable_PlayerY: .res 1 ; $0082: PlayerY: byte
variable_AlternateFrame: .res 1 ; $0083: AlternateFrame: boolean
variable_PlayerVisible: .res 1 ; $0084: PlayerVisible: boolean

.segment "OAM_SHADOW"
; Runtime: page-aligned OAM DMA shadow at $0200-$02FF
runtime_oam_shadow: .res 256 ; $0200: 256-byte page copied to PPU OAM by runtime sprite support

.segment "RUNTIME_DATA"
; Runtime: regular-RAM state kept separate from user variables
runtime_metasprite_x: .res 1 ; $0300: logical screen X for each metasprite instance
runtime_metasprite_y: .res 1 ; $0301: logical screen Y for each metasprite instance
runtime_metasprite_frame: .res 1 ; $0302: selected symbolic frame for each metasprite instance
runtime_metasprite_flags: .res 1 ; $0303: visibility and whole-metasprite flip flags
runtime_metasprite_current_instance: .res 1 ; $0304: instance currently being rendered
runtime_metasprite_frame_remaining: .res 1 ; $0305: components left in selected frame
runtime_metasprite_slots_remaining: .res 1 ; $0306: reserved OAM slots left to visit
runtime_metasprite_oam_offset: .res 1 ; $0307: current OAM shadow byte offset
runtime_metasprite_offset_x: .res 1 ; $0308: signed component X offset
runtime_metasprite_offset_y: .res 1 ; $0309: signed component Y offset
runtime_metasprite_tile: .res 1 ; $030A: current component CHR tile
runtime_metasprite_attributes: .res 1 ; $030B: current component attributes
runtime_ppuctrl_shadow: .res 1 ; $030C: authoritative PPUCTRL value restored each NMI
runtime_ppumask_shadow: .res 1 ; $030D: authoritative PPUMASK value restored each NMI
runtime_scroll_x_shadow: .res 1 ; $030E: authoritative horizontal scroll restored each NMI
runtime_scroll_y_shadow: .res 1 ; $030F: authoritative vertical scroll restored each NMI

.segment "USER_VARIABLES"
; Source: non-promoted variables and all parameters in regular CPU RAM
    ; no user variables

.segment "CODE"

; Interrupt handlers
NMI:
    pha
    txa
    pha
    tya
    pha

    inc runtime_frame_counter ; volatile 8-bit counter, wraps modulo 256
    lda #$01
    sta runtime_frame_ready   ; advisory; frame counter is authoritative
    ; Runtime: upload the complete OAM shadow during VBlank
    lda #$00
    sta $2003               ; OAM address
    lda #>runtime_oam_shadow
    sta $4014               ; page-aligned OAM DMA

    ; Runtime: authoritative final PPU state after all VBlank work
    bit $2002               ; reset the shared PPU write latch
    lda runtime_ppuctrl_shadow
    sta $2000
    lda runtime_scroll_x_shadow
    sta $2005               ; scroll X (first write)
    lda runtime_scroll_y_shadow
    sta $2005               ; scroll Y (second write)
    lda runtime_ppumask_shadow
    sta $2001

    pla
    tay
    pla
    tax
    pla
    rti

IRQ:
    rti

; Source: implicit NES runtime initialization
RESET:
    sei
    cld
    ldx #$40
    stx $4017               ; disable frame counter IRQ
    ldx #$FF
    txs
    inx                     ; X = 0
    stx $2000               ; disable NMI
    stx $2001               ; disable rendering
    stx $4010               ; disable DMC IRQ
    bit $2002               ; clear the vblank latch

@wait_vblank_1:
    bit $2002
    bpl @wait_vblank_1

    txa
@clear_ram:
    sta $0000, x
    sta $0100, x
    sta $0200, x
    sta $0300, x
    sta $0400, x
    sta $0500, x
    sta $0600, x
    sta $0700, x
    inx
    bne @clear_ram

@wait_vblank_2:
    bit $2002
    bpl @wait_vblank_2

    ; Runtime: hide all 64 sprites before the first OAM DMA
    lda #$FF
    ldx #$00
@hide_all_sprites:
    sta runtime_oam_shadow, x
    inx
    inx
    inx
    inx
    bne @hide_all_sprites

    ; Runtime: initialize statically owned metasprite instances hidden
    lda #$00
    sta runtime_metasprite_frame

; Source: nes.import_metasprite(player)

; Source: Player := value
    lda #$00              ; static metasprite reservation
    sta variable_Player

; Source: PlayerX := value
    lda #$70
    sta variable_PlayerX

; Source: PlayerY := value
    lda #$68
    sta variable_PlayerY

; Source: AlternateFrame := value
    lda #$00              ; false
    sta variable_AlternateFrame

; Source: PlayerVisible := value
    lda #$01              ; true
    sta variable_PlayerVisible

; Source: nes.set_sprite_palette(index, color0, color1, color2, color3)
; Initialization: color 0 uses the canonical universal color
    bit $2002               ; reset PPU address latch
    lda #$3F
    sta $2006               ; palette address, high byte
    lda #$00
    sta $2006               ; palette address, low byte
    lda #$0F
    sta $2007
    bit $2002               ; reset PPU address latch
    lda #$3F
    sta $2006               ; palette address, high byte
    lda #$11
    sta $2006               ; palette address, low byte
    lda #$16
    sta $2007
    lda #$27
    sta $2007
    lda #$30
    sta $2007

; Source: nes.metasprite_set_position(...)
    lda variable_PlayerX
    sta runtime_metasprite_offset_x ; evaluate the value once
    lda variable_PlayerY
    sta runtime_metasprite_offset_y ; evaluate Y once
    lda variable_Player
    jsr runtime_metasprite_set_position

; Source: nes.metasprite_show(...)
    lda variable_Player
    jsr runtime_metasprite_show

; Source: nes.set_background_color(value)
    lda #$3F
    sta $2006               ; universal palette address, high byte
    lda #$00
    sta $2006               ; low byte
    lda #$0F
    sta $2007

; Source: nes.on_update(Update)
; Runtime: static callback registration; no state emitted

; Source: nes.run
; Runtime: defer rendering-sensitive setup to VBlank
@wait_render_vblank_0:
    bit $2002
    bpl @wait_render_vblank_0
    lda runtime_ppuctrl_shadow
    ora #$80
    sta runtime_ppuctrl_shadow ; preserve bits and enable NMI
    sta $2000
    lda runtime_scroll_x_shadow ; zero-filled default scroll X
    sta $2005
    lda runtime_scroll_y_shadow ; zero-filled default scroll Y
    sta $2005
    lda runtime_ppumask_shadow
    ora #$1E
    sta runtime_ppumask_shadow ; preserve bits and enable rendering
    sta $2001

; Runtime: frame-synchronized update callback loop
    ; Establish the frame baseline once when the callback loop starts.
    lda runtime_frame_counter
    sta runtime_last_processed_frame
@runtime_update_loop:
    lda runtime_frame_counter
    cmp runtime_last_processed_frame
    beq @runtime_update_loop
    ; Accept only the newest pending frame; never replay a backlog.
    sta runtime_last_processed_frame
    lda #$00
    sta runtime_frame_ready ; advisory latch only; counter comparison is authoritative
    lda runtime_last_processed_frame
    jsr runtime_update_controllers ; exactly once for the accepted frame
    jsr procedure_Update
    jmp @runtime_update_loop

; Runtime: idempotent controller update for one newly processed frame
runtime_update_controllers:
    tax                     ; X keeps the caller's accepted frame value
    lda runtime_controller_poll_valid
    beq @controllers_need_poll
    txa
    cmp runtime_controller_polled_frame
    beq @controllers_already_current
@controllers_need_poll:
    lda #$01
    sta runtime_controller_poll_valid
    txa
    sta runtime_controller_polled_frame
    lda runtime_controller_1_current
    sta runtime_controller_1_previous
    lda runtime_controller_2_current
    sta runtime_controller_2_previous
    jsr runtime_read_controller_ports
@controllers_already_current:
    rts

; Runtime: isolated standard NES serial controller protocol
; Bit layout: A, B, Select, Start, Up, Down, Left, Right = bits 0..7.
runtime_read_controller_ports:
    lda #$01
    sta $4016               ; latch both controllers
    lda #$00
    sta $4016               ; begin serial reads
    sta runtime_controller_1_current
    sta runtime_controller_2_current
    ldx #$08
@read_controller_bits:
    lda $4016
    lsr a                   ; controller 1 serial bit -> carry
    ror runtime_controller_1_current
    lda $4017
    lsr a                   ; controller 2 serial bit -> carry
    ror runtime_controller_2_current
    dex
    bne @read_controller_bits
    rts

; Runtime: bounded table-driven metasprite rendering into the OAM shadow
; Flags: bit 0 visible, bit 1 whole horizontal flip, bit 2 whole vertical flip.
runtime_metasprite_set_position:
    cmp #$01
    bcs @metasprite_set_position_done
    tax
    lda runtime_metasprite_offset_x
    sta runtime_metasprite_x, x
    lda runtime_metasprite_offset_y
    sta runtime_metasprite_y, x
    txa
    jsr runtime_metasprite_render
@metasprite_set_position_done:
    rts

runtime_metasprite_set_frame:
    cmp #$01
    bcs @metasprite_set_frame_done
    tax
    lda runtime_metasprite_offset_x
    cmp #$06
    bcs @metasprite_set_frame_done
    tay
    lda metasprite_frame_asset, y
    cmp metasprite_instance_asset, x
    bne @metasprite_set_frame_done ; dynamic cross-asset frames are ignored
    tya
    sta runtime_metasprite_frame, x
    txa
    jsr runtime_metasprite_render
@metasprite_set_frame_done:
    rts

runtime_metasprite_hide:
    cmp #$01
    bcs @metasprite_hide_done
    tax
    lda runtime_metasprite_flags, x
    and #$FE
    sta runtime_metasprite_flags, x
    txa
    jsr runtime_metasprite_render
@metasprite_hide_done:
    rts

runtime_metasprite_show:
    cmp #$01
    bcs @metasprite_show_done
    tax
    lda runtime_metasprite_flags, x
    ora #$01
    sta runtime_metasprite_flags, x
    txa
    jsr runtime_metasprite_render
@metasprite_show_done:
    rts

runtime_metasprite_set_flip_horizontal:
    cmp #$01
    bcs @metasprite_set_flip_horizontal_done
    tax
    lda runtime_metasprite_offset_x
    beq @metasprite_set_flip_horizontal_clear
    lda runtime_metasprite_flags, x
    ora #$02
    jmp @metasprite_set_flip_horizontal_store
@metasprite_set_flip_horizontal_clear:
    lda runtime_metasprite_flags, x
    and #$FD
@metasprite_set_flip_horizontal_store:
    sta runtime_metasprite_flags, x
    txa
    jsr runtime_metasprite_render
@metasprite_set_flip_horizontal_done:
    rts

runtime_metasprite_set_flip_vertical:
    cmp #$01
    bcs @metasprite_set_flip_vertical_done
    tax
    lda runtime_metasprite_offset_x
    beq @metasprite_set_flip_vertical_clear
    lda runtime_metasprite_flags, x
    ora #$04
    jmp @metasprite_set_flip_vertical_store
@metasprite_set_flip_vertical_clear:
    lda runtime_metasprite_flags, x
    and #$FB
@metasprite_set_flip_vertical_store:
    sta runtime_metasprite_flags, x
    txa
    jsr runtime_metasprite_render
@metasprite_set_flip_vertical_done:
    rts

runtime_metasprite_render:
    sta runtime_metasprite_current_instance
    tax
    lda metasprite_instance_slot_pointer_low, x
    sta runtime_metasprite_slot_pointer
    lda metasprite_instance_slot_pointer_high, x
    sta runtime_metasprite_slot_pointer + 1
    ldy #$00
    lda (runtime_metasprite_slot_pointer), y
    sta runtime_metasprite_slots_remaining
    jsr runtime_metasprite_advance_slot_pointer
    lda runtime_metasprite_flags, x
    and #$01
    bne @metasprite_visible
    jmp @metasprite_hide_slots
@metasprite_visible:
    lda runtime_metasprite_frame, x
    tay
    lda metasprite_frame_pointer_low, y
    sta runtime_metasprite_frame_pointer
    lda metasprite_frame_pointer_high, y
    sta runtime_metasprite_frame_pointer + 1
    ldy #$00
    lda (runtime_metasprite_frame_pointer), y
    sta runtime_metasprite_frame_remaining
    jsr runtime_metasprite_advance_frame_pointer
@metasprite_slot_loop:
    lda runtime_metasprite_slots_remaining
    bne @metasprite_slot_available
    jmp @metasprite_render_done
@metasprite_slot_available:
    ldy #$00
    lda (runtime_metasprite_slot_pointer), y
    asl a
    asl a
    sta runtime_metasprite_oam_offset
    jsr runtime_metasprite_advance_slot_pointer
    lda runtime_metasprite_frame_remaining
    bne @metasprite_component_available
    jmp @metasprite_hide_one
@metasprite_component_available:
    dec runtime_metasprite_frame_remaining
    ldy #$00
    lda (runtime_metasprite_frame_pointer), y
    sta runtime_metasprite_offset_x
    jsr runtime_metasprite_advance_frame_pointer
    ldy #$00
    lda (runtime_metasprite_frame_pointer), y
    sta runtime_metasprite_offset_y
    jsr runtime_metasprite_advance_frame_pointer
    ldy #$00
    lda (runtime_metasprite_frame_pointer), y
    sta runtime_metasprite_tile
    jsr runtime_metasprite_advance_frame_pointer
    ldy #$00
    lda (runtime_metasprite_frame_pointer), y
    sta runtime_metasprite_attributes
    jsr runtime_metasprite_advance_frame_pointer
    ldx runtime_metasprite_current_instance
    lda runtime_metasprite_flags, x
    and #$02
    beq @metasprite_x_not_flipped
    lda runtime_metasprite_offset_x
    eor #$FF
    sec
    sbc #$07                ; -offset - 8 for an 8-pixel tile
    sta runtime_metasprite_offset_x
    lda runtime_metasprite_attributes
    eor #$40                ; combine component and whole flip
    sta runtime_metasprite_attributes
@metasprite_x_not_flipped:
    lda runtime_metasprite_flags, x
    and #$04
    beq @metasprite_y_not_flipped
    lda runtime_metasprite_offset_y
    eor #$FF
    sec
    sbc #$07
    sta runtime_metasprite_offset_y
    lda runtime_metasprite_attributes
    eor #$80
    sta runtime_metasprite_attributes
@metasprite_y_not_flipped:
    lda runtime_metasprite_offset_x
    bmi @metasprite_x_negative
    clc
    adc runtime_metasprite_x, x
    bcs @metasprite_hide_one
    cmp #$F9                ; a full 8-pixel tile ends at X = 255
    bcs @metasprite_hide_one
    jmp @metasprite_x_valid
@metasprite_x_negative:
    eor #$FF
    clc
    adc #$01
    sta runtime_metasprite_offset_x
    lda runtime_metasprite_x, x
    cmp runtime_metasprite_offset_x
    bcc @metasprite_hide_one
    sec
    sbc runtime_metasprite_offset_x
    cmp #$F9                ; negative offsets still obey the right edge
    bcs @metasprite_hide_one
@metasprite_x_valid:
    ldy runtime_metasprite_oam_offset
    sta runtime_oam_shadow + 3, y
    lda runtime_metasprite_offset_y
    bmi @metasprite_y_negative
    clc
    adc runtime_metasprite_y, x
    bcs @metasprite_hide_one
    cmp #$E9                ; logical top 1..232 is fully visible
    bcs @metasprite_hide_one
    jmp @metasprite_y_range
@metasprite_y_negative:
    eor #$FF
    clc
    adc #$01
    sta runtime_metasprite_offset_y
    lda runtime_metasprite_y, x
    cmp runtime_metasprite_offset_y
    bcc @metasprite_hide_one
    sec
    sbc runtime_metasprite_offset_y
@metasprite_y_range:
    beq @metasprite_hide_one ; $FF is reserved as the hidden OAM Y
    cmp #$E9
    bcs @metasprite_hide_one
    sec
    sbc #$01                ; logical top -> NES OAM Y convention
    pha
    ldy runtime_metasprite_oam_offset
    lda runtime_metasprite_tile
    sta runtime_oam_shadow + 1, y
    lda runtime_metasprite_attributes
    sta runtime_oam_shadow + 2, y
    pla
    sta runtime_oam_shadow, y ; publish Y last
    jmp @metasprite_next_slot
@metasprite_hide_one:
    ldy runtime_metasprite_oam_offset
    lda #$FF
    sta runtime_oam_shadow, y
@metasprite_next_slot:
    dec runtime_metasprite_slots_remaining
    jmp @metasprite_slot_loop
@metasprite_hide_slots:
    lda runtime_metasprite_slots_remaining
    beq @metasprite_render_done
    ldy #$00
    lda (runtime_metasprite_slot_pointer), y
    asl a
    asl a
    tay
    lda #$FF
    sta runtime_oam_shadow, y
    jsr runtime_metasprite_advance_slot_pointer
    dec runtime_metasprite_slots_remaining
    jmp @metasprite_hide_slots
@metasprite_render_done:
    rts

runtime_metasprite_advance_frame_pointer:
    inc runtime_metasprite_frame_pointer
    bne @metasprite_frame_pointer_done
    inc runtime_metasprite_frame_pointer + 1
@metasprite_frame_pointer_done:
    rts

runtime_metasprite_advance_slot_pointer:
    inc runtime_metasprite_slot_pointer
    bne @metasprite_slot_pointer_done
    inc runtime_metasprite_slot_pointer + 1
@metasprite_slot_pointer_done:
    rts


; Source: procedure declarations
; Procedure: Update
procedure_Update:

; Source: if condition then
    ; nes.controller_down($01, nes.button_left): branch result
    lda runtime_controller_1_current
    and #$40
    bne @if_then_1
    jmp @if_else_3       ; long-branch-safe false path
@if_then_1:

; Source: if condition then
    ; comparison >: direct right operand
    lda variable_PlayerX
    cmp #$0C
    beq @comparison_branch_false_6
    bcs @if_then_4
@comparison_branch_false_6:
    jmp @if_end_5       ; long-branch-safe false path
@if_then_4:

; Source: dec(PlayerX)
    dec variable_PlayerX
@if_end_5:

; Source: nes.metasprite_set_flip_horizontal(...)
    lda #$01              ; true
    sta runtime_metasprite_offset_x ; evaluate the value once
    lda variable_Player
    jsr runtime_metasprite_set_flip_horizontal
    jmp @if_end_2
@if_else_3:

; Source: if condition then
    ; nes.controller_down($01, nes.button_right): branch result
    lda runtime_controller_1_current
    and #$80
    bne @if_then_7
    jmp @if_end_8       ; long-branch-safe false path
@if_then_7:

; Source: if condition then
    ; comparison <: direct right operand
    lda variable_PlayerX
    cmp #$F4
    bcc @if_then_9
    jmp @if_end_10       ; long-branch-safe false path
@if_then_9:

; Source: inc(PlayerX)
    inc variable_PlayerX
@if_end_10:

; Source: nes.metasprite_set_flip_horizontal(...)
    lda #$00              ; false
    sta runtime_metasprite_offset_x ; evaluate the value once
    lda variable_Player
    jsr runtime_metasprite_set_flip_horizontal
@if_end_8:
@if_end_2:

; Source: if condition then
    ; nes.controller_down($01, nes.button_up): branch result
    lda runtime_controller_1_current
    and #$10
    bne @if_then_11
    jmp @if_else_13       ; long-branch-safe false path
@if_then_11:

; Source: if condition then
    ; comparison >: direct right operand
    lda variable_PlayerY
    cmp #$0D
    beq @comparison_branch_false_16
    bcs @if_then_14
@comparison_branch_false_16:
    jmp @if_end_15       ; long-branch-safe false path
@if_then_14:

; Source: dec(PlayerY)
    dec variable_PlayerY
@if_end_15:
    jmp @if_end_12
@if_else_13:

; Source: if condition then
    ; nes.controller_down($01, nes.button_down): branch result
    lda runtime_controller_1_current
    and #$20
    bne @if_then_17
    jmp @if_end_18       ; long-branch-safe false path
@if_then_17:

; Source: if condition then
    ; comparison <: direct right operand
    lda variable_PlayerY
    cmp #$E4
    bcc @if_then_19
    jmp @if_end_20       ; long-branch-safe false path
@if_then_19:

; Source: inc(PlayerY)
    inc variable_PlayerY
@if_end_20:
@if_end_18:
@if_end_12:

; Source: if condition then
    ; nes.controller_pressed($01, nes.button_a): branch result
    lda runtime_controller_1_current
    and #$01
    beq @controller_branch_false_23
    lda runtime_controller_1_previous
    and #$01
    beq @if_then_21
@controller_branch_false_23:
    jmp @if_end_22       ; long-branch-safe false path
@if_then_21:

; Source: AlternateFrame := value
    ; boolean not
    lda variable_AlternateFrame
    beq @not_true_24
    lda #$00              ; false
    jmp @not_end_25
@not_true_24:
    lda #$01              ; true
@not_end_25:
    sta variable_AlternateFrame

; Source: if condition then
    lda variable_AlternateFrame
    bne @if_then_26
    jmp @if_else_28       ; long-branch-safe false path
@if_then_26:

; Source: nes.metasprite_set_frame(...)
    lda #$02
    sta runtime_metasprite_offset_x ; evaluate the value once
    lda variable_Player
    jsr runtime_metasprite_set_frame
    jmp @if_end_27
@if_else_28:

; Source: nes.metasprite_set_frame(...)
    lda #$00
    sta runtime_metasprite_offset_x ; evaluate the value once
    lda variable_Player
    jsr runtime_metasprite_set_frame
@if_end_27:
@if_end_22:

; Source: if condition then
    ; nes.controller_pressed($01, nes.button_select): branch result
    lda runtime_controller_1_current
    and #$04
    beq @controller_branch_false_31
    lda runtime_controller_1_previous
    and #$04
    beq @if_then_29
@controller_branch_false_31:
    jmp @if_end_30       ; long-branch-safe false path
@if_then_29:

; Source: PlayerVisible := value
    ; boolean not
    lda variable_PlayerVisible
    beq @not_true_32
    lda #$00              ; false
    jmp @not_end_33
@not_true_32:
    lda #$01              ; true
@not_end_33:
    sta variable_PlayerVisible

; Source: if condition then
    lda variable_PlayerVisible
    bne @if_then_34
    jmp @if_else_36       ; long-branch-safe false path
@if_then_34:

; Source: nes.metasprite_show(...)
    lda variable_Player
    jsr runtime_metasprite_show
    jmp @if_end_35
@if_else_36:

; Source: nes.metasprite_hide(...)
    lda variable_Player
    jsr runtime_metasprite_hide
@if_end_35:
@if_end_30:

; Source: nes.metasprite_set_position(...)
    lda variable_PlayerX
    sta runtime_metasprite_offset_x ; evaluate the value once
    lda variable_PlayerY
    sta runtime_metasprite_offset_y ; evaluate Y once
    lda variable_Player
    jsr runtime_metasprite_set_position
    rts

; Asset: immutable metasprite tables in PRG-ROM
metasprite_frame_pointer_low:
    .byte <metasprite_frame_0, <metasprite_frame_1, <metasprite_frame_2, <metasprite_frame_3, <metasprite_frame_4, <metasprite_frame_5
metasprite_frame_pointer_high:
    .byte >metasprite_frame_0, >metasprite_frame_1, >metasprite_frame_2, >metasprite_frame_3, >metasprite_frame_4, >metasprite_frame_5
metasprite_frame_asset:
    .byte $00, $00, $00, $00, $00, $00
metasprite_instance_slot_pointer_low:
    .byte <metasprite_instance_slots_0
metasprite_instance_slot_pointer_high:
    .byte >metasprite_instance_slots_0
metasprite_instance_asset:
    .byte $00
metasprite_frame_0:
    .byte $07 ; player.idle_0
    .byte $FC, $F4, $00, $00
    .byte $04, $F4, $00, $40
    .byte $FC, $FC, $01, $00
    .byte $04, $FC, $02, $00
    .byte $F4, $04, $03, $00
    .byte $FC, $04, $04, $00
    .byte $04, $04, $05, $00
metasprite_frame_1:
    .byte $07 ; player.idle_1
    .byte $FC, $F4, $00, $00
    .byte $04, $F4, $00, $40
    .byte $FC, $FC, $01, $00
    .byte $04, $FC, $02, $00
    .byte $F4, $04, $03, $00
    .byte $FC, $04, $04, $00
    .byte $04, $04, $05, $00
metasprite_frame_2:
    .byte $07 ; player.idle_2
    .byte $FC, $F4, $06, $00
    .byte $04, $F4, $06, $40
    .byte $FC, $FC, $07, $00
    .byte $04, $FC, $08, $00
    .byte $F4, $04, $03, $00
    .byte $FC, $04, $09, $00
    .byte $04, $04, $0A, $00
metasprite_frame_3:
    .byte $07 ; player.idle_3
    .byte $FC, $F4, $0B, $00
    .byte $04, $F4, $0B, $40
    .byte $FC, $FC, $0C, $00
    .byte $04, $FC, $0D, $00
    .byte $F4, $04, $0E, $00
    .byte $FC, $04, $0F, $00
    .byte $04, $04, $10, $00
metasprite_frame_4:
    .byte $07 ; player.idle_4
    .byte $FC, $F4, $0B, $00
    .byte $04, $F4, $0B, $40
    .byte $FC, $FC, $0C, $00
    .byte $04, $FC, $0D, $00
    .byte $F4, $04, $0E, $00
    .byte $FC, $04, $0F, $00
    .byte $04, $04, $10, $00
metasprite_frame_5:
    .byte $07 ; player.idle_5
    .byte $FC, $F4, $06, $00
    .byte $04, $F4, $06, $40
    .byte $FC, $FC, $07, $00
    .byte $04, $FC, $08, $00
    .byte $F4, $04, $11, $00
    .byte $FC, $04, $12, $00
    .byte $04, $04, $13, $00
metasprite_instance_slots_0:
    .byte $07, $00, $01, $02, $03, $04, $05, $06

.segment "VECTORS"
    .word NMI
    .word RESET
    .word IRQ

.segment "CHR"
    ; Asset: configured CHR-ROM bytes
    .byte $00, $00, $00, $00, $00, $03, $0C, $10, $00, $00, $00, $00, $00, $00, $03, $0F
    .byte $10, $10, $18, $1C, $1D, $1D, $1C, $0C, $0F, $0F, $07, $03, $03, $03, $03, $03
    .byte $04, $04, $04, $04, $9C, $FC, $F4, $F6, $F8, $F8, $F8, $F8, $68, $68, $F8, $F8
    .byte $00, $00, $01, $1F, $1E, $11, $0E, $00, $00, $00, $00, $01, $0F, $0E, $00, $00
    .byte $07, $2F, $F3, $C6, $1F, $DF, $25, $00, $00, $00, $2C, $F9, $F8, $20, $02, $00
    .byte $FD, $FB, $E7, $2F, $EF, $F5, $52, $0C, $02, $04, $18, $D0, $10, $0A, $2C, $00
    .byte $00, $00, $00, $00, $00, $00, $03, $0C, $00, $00, $00, $00, $00, $00, $00, $03
    .byte $10, $10, $10, $18, $1C, $1D, $1D, $1C, $0F, $0F, $0F, $07, $03, $03, $03, $03
    .byte $08, $04, $04, $04, $04, $9C, $FC, $F6, $F0, $F8, $F8, $F8, $F8, $68, $68, $F8
    .byte $0C, $2F, $FF, $C6, $1F, $DF, $25, $00, $03, $00, $20, $F9, $F8, $20, $02, $00
    .byte $F5, $FB, $E7, $2F, $EF, $F5, $52, $0C, $FA, $04, $18, $D0, $10, $0A, $2C, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $03, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $0C, $10, $10, $10, $18, $1C, $1D, $1D, $03, $0F, $0F, $0F, $07, $03, $03, $03
    .byte $30, $08, $04, $04, $04, $04, $9C, $FE, $C0, $F0, $F8, $F8, $F8, $F8, $68, $68
    .byte $00, $00, $00, $03, $3F, $3C, $23, $1C, $00, $00, $00, $00, $03, $1F, $1C, $00
    .byte $1C, $0C, $4F, $FF, $86, $3F, $B7, $40, $03, $03, $00, $40, $F9, $F0, $40, $00
    .byte $F5, $F3, $E7, $EF, $2F, $F5, $72, $0C, $FA, $FC, $18, $10, $D0, $0A, $0C, $00
    .byte $00, $00, $00, $01, $1F, $1E, $11, $0E, $00, $00, $00, $00, $01, $0F, $0E, $00
    .byte $0C, $0F, $2F, $F3, $C6, $1F, $DF, $20, $03, $00, $00, $2C, $F9, $F8, $20, $00
    .byte $F5, $FB, $E7, $EF, $2F, $F5, $72, $0C, $FA, $04, $18, $10, $D0, $0A, $0C, $00
    .byte $04, $04, $04, $04, $9C, $FC, $F4, $F4, $F8, $F8, $F8, $F8, $68, $68, $F8, $F8
    .byte $07, $2F, $F3, $C6, $1F, $DB, $21, $00, $00, $00, $2C, $F9, $F8, $20, $00, $00
    .byte $FE, $F9, $E7, $0F, $F7, $F7, $A9, $06, $00, $06, $18, $F0, $08, $08, $46, $00
    .byte $08, $04, $04, $04, $04, $9C, $FC, $F4, $F0, $F8, $F8, $F8, $F8, $68, $68, $F8
    .byte $00, $00, $00, $00, $0F, $0F, $08, $07, $00, $00, $00, $00, $00, $07, $07, $00
    .byte $0C, $07, $17, $F9, $E3, $0F, $EF, $11, $03, $00, $00, $16, $FC, $FC, $10, $00
    .byte $F6, $FD, $F3, $F7, $17, $FB, $F9, $66, $F8, $02, $0C, $08, $E8, $04, $06, $80
    .byte $10, $10, $1C, $1E, $1E, $1E, $1E, $0E, $0F, $0F, $03, $01, $01, $01, $01, $01
    .byte $04, $04, $04, $04, $CC, $FC, $7C, $7E, $F8, $F8, $F8, $F8, $B0, $B0, $F8, $F8
    .byte $00, $00, $00, $0F, $0F, $08, $07, $00, $00, $00, $00, $00, $07, $07, $00, $00
    .byte $07, $17, $F9, $E3, $0F, $EF, $16, $03, $00, $00, $16, $FC, $FC, $10, $01, $00
    .byte $FD, $F9, $FB, $0B, $FB, $F9, $AE, $10, $02, $06, $04, $F4, $04, $06, $10, $00
    .byte $00, $00, $00, $07, $07, $04, $03, $00, $00, $00, $00, $00, $03, $03, $00, $00
    .byte $07, $0F, $7D, $F1, $87, $77, $8E, $00, $00, $00, $0A, $7E, $FE, $88, $00, $00
    .byte $FD, $F9, $FB, $0B, $FB, $E9, $2E, $18, $02, $06, $04, $F4, $04, $16, $10, $00
    .byte $10, $10, $10, $1C, $1E, $1E, $1E, $1E, $0F, $0F, $0F, $03, $01, $01, $01, $01
    .byte $08, $04, $04, $04, $04, $CC, $FC, $7C, $F0, $F8, $F8, $F8, $F8, $B0, $B0, $F8
    .byte $0E, $07, $17, $F9, $E3, $0F, $EF, $13, $01, $00, $00, $16, $FC, $FC, $10, $00
    .byte $7E, $FD, $F9, $FB, $0B, $FB, $F9, $2E, $F8, $02, $06, $04, $F4, $04, $06, $10
    .byte $0E, $07, $2F, $F3, $C6, $1F, $DB, $21, $01, $00, $00, $2C, $F9, $F8, $20, $00
    .byte $7E, $FD, $F3, $F7, $17, $FB, $F9, $66, $F8, $02, $0C, $08, $E8, $04, $06, $80
    .byte $07, $2F, $F3, $C6, $1F, $D9, $20, $00, $00, $00, $2C, $F9, $F8, $20, $00, $00
    .byte $FD, $F3, $F7, $17, $FB, $A9, $A6, $40, $02, $0C, $08, $E8, $04, $46, $40, $00
    .byte $FE, $F9, $E7, $0F, $F7, $F7, $A9, $66, $00, $06, $18, $F0, $08, $08, $46, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
