; Generated by nes-pascal for program PaletteSupport
; Mapper 0, 32 KiB PRG-ROM, 8 KiB CHR-ROM

.segment "HEADER"
    .byte "NES", $1A
    .byte 2                  ; PRG-ROM banks, 16 KiB each
    .byte 1                  ; CHR-ROM banks, 8 KiB each
    .byte $00                ; mapper and mirroring flags
    .byte $00                ; mapper upper bits
    .byte $00, $00, $00, $00, $00, $00, $00, $00

.segment "ZERO_PAGE_RUNTIME": zeropage
; Runtime: frame synchronization state, isolated from compiler temporaries
runtime_frame_counter: .res 1 ; $0000: volatile 8-bit counter incremented once by each NMI
runtime_frame_ready: .res 1 ; $0001: advisory frame-ready signal consumed by main frame waits
runtime_last_processed_frame: .res 1 ; $0002: persistent update-loop frame baseline
runtime_controller_1_current: .res 1 ; $0003: controller 1 state for the newest processed frame
runtime_controller_1_previous: .res 1 ; $0004: controller 1 state for the preceding processed frame
runtime_controller_2_current: .res 1 ; $0005: controller 2 state for the newest processed frame
runtime_controller_2_previous: .res 1 ; $0006: controller 2 state for the preceding processed frame
runtime_controller_polled_frame: .res 1 ; $0007: frame counter value of the most recent controller poll
runtime_controller_poll_valid: .res 1 ; $0008: distinguishes an initial zero byte from a completed frame-zero poll

.segment "ZERO_PAGE_TEMPORARIES": zeropage
; Compiler: mandatory expression and loop storage in Zero Page
    ; no compiler temporaries required

.segment "ZERO_PAGE_VARIABLES": zeropage
; Source: optional global-variable promotion with regular-RAM fallback
    ; no globals selected for automatic promotion

.segment "OAM_SHADOW"
; Runtime: page-aligned OAM DMA shadow at $0200-$02FF
runtime_oam_shadow: .res 256 ; $0200: 256-byte page copied to PPU OAM by runtime sprite support

.segment "RUNTIME_DATA"
; Runtime: regular-RAM state kept separate from user variables
runtime_sprite_zero_pending_x: .res 1 ; $0300: staged sprite 0 X coordinate
runtime_sprite_zero_pending_y: .res 1 ; $0301: staged sprite 0 Y coordinate
runtime_sprite_zero_pending_tile: .res 1 ; $0302: staged sprite 0 tile index
runtime_sprite_zero_pending_attributes: .res 1 ; $0303: staged sprite 0 attributes
runtime_sprite_zero_ready: .res 1 ; $0304: atomic sprite 0 staging commit flag
runtime_palette_shadow: .res 32 ; $0305: canonical 32-byte background and sprite palette shadow
runtime_palette_background_0_dirty: .res 1 ; $0325: atomic publish flag for background palette 0
runtime_palette_background_1_dirty: .res 1 ; $0326: atomic publish flag for background palette 1
runtime_palette_background_2_dirty: .res 1 ; $0327: atomic publish flag for background palette 2
runtime_palette_background_3_dirty: .res 1 ; $0328: atomic publish flag for background palette 3
runtime_palette_sprite_0_dirty: .res 1 ; $0329: atomic publish flag for sprite palette 0
runtime_palette_sprite_1_dirty: .res 1 ; $032A: atomic publish flag for sprite palette 1
runtime_palette_sprite_2_dirty: .res 1 ; $032B: atomic publish flag for sprite palette 2
runtime_palette_sprite_3_dirty: .res 1 ; $032C: atomic publish flag for sprite palette 3
runtime_palette_universal_dirty: .res 1 ; $032D: atomic publish flag for the universal background color
runtime_ppuctrl_shadow: .res 1 ; $032E: authoritative PPUCTRL value restored each NMI
runtime_ppumask_shadow: .res 1 ; $032F: authoritative PPUMASK value restored each NMI
runtime_scroll_x_shadow: .res 1 ; $0330: authoritative horizontal scroll restored each NMI
runtime_scroll_y_shadow: .res 1 ; $0331: authoritative vertical scroll restored each NMI

.segment "USER_VARIABLES"
; Source: non-promoted variables and all parameters in regular CPU RAM
    ; no user variables

.segment "CODE"

; Interrupt handlers
NMI:
    pha
    txa
    pha
    tya
    pha

    inc runtime_frame_counter ; volatile 8-bit counter, wraps modulo 256
    lda #$01
    sta runtime_frame_ready   ; advisory; frame counter is authoritative

    ; Runtime: commit the legacy helper's complete staged sprite 0
    lda runtime_sprite_zero_ready
    beq @skip_sprite_zero_commit
    lda #$00
    sta runtime_sprite_zero_ready
    lda runtime_sprite_zero_pending_y
    sta runtime_oam_shadow
    lda runtime_sprite_zero_pending_tile
    sta runtime_oam_shadow + 1
    lda runtime_sprite_zero_pending_attributes
    sta runtime_oam_shadow + 2
    lda runtime_sprite_zero_pending_x
    sta runtime_oam_shadow + 3
@skip_sprite_zero_commit:
    ; Runtime: upload the complete OAM shadow during VBlank
    lda #$00
    sta $2003               ; OAM address
    lda #>runtime_oam_shadow
    sta $4014               ; page-aligned OAM DMA

    ; Runtime: consume bounded queued palette updates before user VBlank work
    jsr runtime_upload_queued_palettes

    ; Runtime: authoritative final PPU state after all VBlank work
    bit $2002               ; reset the shared PPU write latch
    lda runtime_ppuctrl_shadow
    sta $2000
    lda runtime_scroll_x_shadow
    sta $2005               ; scroll X (first write)
    lda runtime_scroll_y_shadow
    sta $2005               ; scroll Y (second write)
    lda runtime_ppumask_shadow
    sta $2001

    pla
    tay
    pla
    tax
    pla
    rti

IRQ:
    rti

; Source: implicit NES runtime initialization
RESET:
    sei
    cld
    ldx #$40
    stx $4017               ; disable frame counter IRQ
    ldx #$FF
    txs
    inx                     ; X = 0
    stx $2000               ; disable NMI
    stx $2001               ; disable rendering
    stx $4010               ; disable DMC IRQ
    bit $2002               ; clear the vblank latch

@wait_vblank_1:
    bit $2002
    bpl @wait_vblank_1

    txa
@clear_ram:
    sta $0000, x
    sta $0100, x
    sta $0200, x
    sta $0300, x
    sta $0400, x
    sta $0500, x
    sta $0600, x
    sta $0700, x
    inx
    bne @clear_ram

@wait_vblank_2:
    bit $2002
    bpl @wait_vblank_2

    ; Runtime: hide all 64 sprites before the first OAM DMA
    lda #$FF
    ldx #$00
@hide_all_sprites:
    sta runtime_oam_shadow, x
    inx
    inx
    inx
    inx
    bne @hide_all_sprites

; Source: nes.set_background_palette(index, color0, color1, color2, color3)
; Initialization: color 0 uses the canonical universal color
    bit $2002               ; reset PPU address latch
    lda #$3F
    sta $2006               ; palette address, high byte
    lda #$00
    sta $2006               ; palette address, low byte
    lda #$0F
    sta $2007
    bit $2002               ; reset PPU address latch
    lda #$3F
    sta $2006               ; palette address, high byte
    lda #$01
    sta $2006               ; palette address, low byte
    lda #$00
    sta $2007
    lda #$10
    sta $2007
    lda #$20
    sta $2007
    lda #$0F
    sta runtime_palette_shadow
    lda #$00
    sta runtime_palette_shadow + 1
    lda #$10
    sta runtime_palette_shadow + 2
    lda #$20
    sta runtime_palette_shadow + 3

; Source: nes.set_background_palette(index, color0, color1, color2, color3)
; Initialization: color 0 uses the canonical universal color
    bit $2002               ; reset PPU address latch
    lda #$3F
    sta $2006               ; palette address, high byte
    lda #$00
    sta $2006               ; palette address, low byte
    lda #$21
    sta $2007
    bit $2002               ; reset PPU address latch
    lda #$3F
    sta $2006               ; palette address, high byte
    lda #$01
    sta $2006               ; palette address, low byte
    lda #$01
    sta $2007
    lda #$11
    sta $2007
    lda #$31
    sta $2007
    lda #$21
    sta runtime_palette_shadow
    lda #$01
    sta runtime_palette_shadow + 1
    lda #$11
    sta runtime_palette_shadow + 2
    lda #$31
    sta runtime_palette_shadow + 3

; Source: nes.set_sprite_palette(index, color0, color1, color2, color3)
; Initialization: color 0 uses the canonical universal color
    bit $2002               ; reset PPU address latch
    lda #$3F
    sta $2006               ; palette address, high byte
    lda #$00
    sta $2006               ; palette address, low byte
    lda #$21
    sta $2007
    bit $2002               ; reset PPU address latch
    lda #$3F
    sta $2006               ; palette address, high byte
    lda #$11
    sta $2006               ; palette address, low byte
    lda #$06
    sta $2007
    lda #$16
    sta $2007
    lda #$26
    sta $2007
    lda #$21
    sta runtime_palette_shadow
    lda #$06
    sta runtime_palette_shadow + 17
    lda #$16
    sta runtime_palette_shadow + 18
    lda #$26
    sta runtime_palette_shadow + 19

; Source: nes.set_background_color(value)
    lda #$3F
    sta $2006               ; universal palette address, high byte
    lda #$00
    sta $2006               ; low byte
    lda #$21
    sta $2007
    sta runtime_palette_shadow

; Source: nes.set_sprite_zero(x, y, tile, attributes)
; Runtime: invalidate, stage all bytes, then publish atomically
    lda #$00
    sta runtime_sprite_zero_ready
    lda #$78
    sta runtime_sprite_zero_pending_x
    lda #$70
    sta runtime_sprite_zero_pending_y
    lda #$01
    sta runtime_sprite_zero_pending_tile
    lda #$00
    sta runtime_sprite_zero_pending_attributes
    lda #$01
    sta runtime_sprite_zero_ready

; Source: nes.run
; Runtime: defer rendering-sensitive setup to VBlank
@wait_render_vblank_0:
    bit $2002
    bpl @wait_render_vblank_0
    lda runtime_ppuctrl_shadow
    ora #$80
    sta runtime_ppuctrl_shadow ; preserve bits and enable NMI
    sta $2000
    lda runtime_scroll_x_shadow ; zero-filled default scroll X
    sta $2005
    lda runtime_scroll_y_shadow ; zero-filled default scroll Y
    sta $2005
    lda runtime_ppumask_shadow
    ora #$1E
    sta runtime_ppumask_shadow ; preserve bits and enable rendering
    sta $2001

; Source: nes.wait_frame
; Runtime: wait for the volatile frame counter to change
    lda runtime_frame_counter
@wait_frame_1:
    cmp runtime_frame_counter
    beq @wait_frame_1
    lda #$00
    sta runtime_frame_ready ; consume advisory signal
    lda runtime_frame_counter ; accepted frame for polling
    jsr runtime_update_controllers ; fresh state for this frame

; Source: ChangePalettes
    jsr procedure_ChangePalettes

; Runtime: implicit stable loop after the main program finishes
@runtime_idle_loop:
    jmp @runtime_idle_loop

; Runtime: idempotent controller update for one newly processed frame
runtime_update_controllers:
    tax                     ; X keeps the caller's accepted frame value
    lda runtime_controller_poll_valid
    beq @controllers_need_poll
    txa
    cmp runtime_controller_polled_frame
    beq @controllers_already_current
@controllers_need_poll:
    lda #$01
    sta runtime_controller_poll_valid
    txa
    sta runtime_controller_polled_frame
    lda runtime_controller_1_current
    sta runtime_controller_1_previous
    lda runtime_controller_2_current
    sta runtime_controller_2_previous
    jsr runtime_read_controller_ports
@controllers_already_current:
    rts

; Runtime: isolated standard NES serial controller protocol
; Bit layout: A, B, Select, Start, Up, Down, Left, Right = bits 0..7.
runtime_read_controller_ports:
    lda #$01
    sta $4016               ; latch both controllers
    lda #$00
    sta $4016               ; begin serial reads
    sta runtime_controller_1_current
    sta runtime_controller_2_current
    ldx #$08
@read_controller_bits:
    lda $4016
    lsr a                   ; controller 1 serial bit -> carry
    ror runtime_controller_1_current
    lda $4017
    lsr a                   ; controller 2 serial bit -> carry
    ror runtime_controller_2_current
    dex
    bne @read_controller_bits
    rts

; Runtime: bounded VBlank palette uploader (at most eight triplets and one universal color)
runtime_upload_queued_palettes:
    lda runtime_palette_background_0_dirty
    beq @skip_background_palette_0
    lda #$00
    sta runtime_palette_background_0_dirty            ; consume complete staged palette
    lda #$01
    ldx #$01
    jsr runtime_upload_palette_triplet
@skip_background_palette_0:
    lda runtime_palette_background_1_dirty
    beq @skip_background_palette_1
    lda #$00
    sta runtime_palette_background_1_dirty            ; consume complete staged palette
    lda #$05
    ldx #$05
    jsr runtime_upload_palette_triplet
@skip_background_palette_1:
    lda runtime_palette_background_2_dirty
    beq @skip_background_palette_2
    lda #$00
    sta runtime_palette_background_2_dirty            ; consume complete staged palette
    lda #$09
    ldx #$09
    jsr runtime_upload_palette_triplet
@skip_background_palette_2:
    lda runtime_palette_background_3_dirty
    beq @skip_background_palette_3
    lda #$00
    sta runtime_palette_background_3_dirty            ; consume complete staged palette
    lda #$0D
    ldx #$0D
    jsr runtime_upload_palette_triplet
@skip_background_palette_3:
    lda runtime_palette_sprite_0_dirty
    beq @skip_sprite_palette_0
    lda #$00
    sta runtime_palette_sprite_0_dirty            ; consume complete staged palette
    lda #$11
    ldx #$11
    jsr runtime_upload_palette_triplet
@skip_sprite_palette_0:
    lda runtime_palette_sprite_1_dirty
    beq @skip_sprite_palette_1
    lda #$00
    sta runtime_palette_sprite_1_dirty            ; consume complete staged palette
    lda #$15
    ldx #$15
    jsr runtime_upload_palette_triplet
@skip_sprite_palette_1:
    lda runtime_palette_sprite_2_dirty
    beq @skip_sprite_palette_2
    lda #$00
    sta runtime_palette_sprite_2_dirty            ; consume complete staged palette
    lda #$19
    ldx #$19
    jsr runtime_upload_palette_triplet
@skip_sprite_palette_2:
    lda runtime_palette_sprite_3_dirty
    beq @skip_sprite_palette_3
    lda #$00
    sta runtime_palette_sprite_3_dirty            ; consume complete staged palette
    lda #$1D
    ldx #$1D
    jsr runtime_upload_palette_triplet
@skip_sprite_palette_3:
    lda runtime_palette_universal_dirty
    beq @skip_universal_palette_color
    lda #$00
    sta runtime_palette_universal_dirty ; consume complete staged color
    bit $2002               ; reset PPU address latch
    lda #$3F
    sta $2006
    lda #$00
    sta $2006
    lda runtime_palette_shadow
    sta $2007
@skip_universal_palette_color:
    rts

runtime_upload_palette_triplet:
    tay                     ; preserve target low address
    bit $2002               ; reset PPU address latch
    lda #$3F
    sta $2006
    tya
    sta $2006
    ldy #$03
@palette_triplet_loop:
    lda runtime_palette_shadow, x
    sta $2007
    inx
    dey
    bne @palette_triplet_loop
    rts


; Source: procedure declarations
; Procedure: ChangePalettes
procedure_ChangePalettes:

; Source: nes.set_background_palette(index, color0, color1, color2, color3)
; Runtime: invalidate both publications before staging any bytes
    lda #$00
    sta runtime_palette_background_0_dirty
    sta runtime_palette_universal_dirty
    lda #$0F
    sta runtime_palette_shadow ; canonical universal color
    lda #$01
    sta runtime_palette_shadow + 1
    lda #$11
    sta runtime_palette_shadow + 2
    lda #$21
    sta runtime_palette_shadow + 3
    lda #$01
    sta runtime_palette_universal_dirty
    sta runtime_palette_background_0_dirty

; Source: nes.set_background_palette(index, color0, color1, color2, color3)
; Runtime: invalidate both publications before staging any bytes
    lda #$00
    sta runtime_palette_background_0_dirty
    sta runtime_palette_universal_dirty
    lda #$16
    sta runtime_palette_shadow ; canonical universal color
    lda #$06
    sta runtime_palette_shadow + 1
    lda #$17
    sta runtime_palette_shadow + 2
    lda #$27
    sta runtime_palette_shadow + 3
    lda #$01
    sta runtime_palette_universal_dirty
    sta runtime_palette_background_0_dirty

; Source: nes.set_sprite_palette_color(palette, color, value)
; Runtime: invalidate, stage one color, then publish the palette
    lda #$00
    sta runtime_palette_sprite_0_dirty
    lda #$30
    sta runtime_palette_shadow + 19
    lda #$01
    sta runtime_palette_sprite_0_dirty
    rts

.segment "VECTORS"
    .word NMI
    .word RESET
    .word IRQ

.segment "CHR"
    ; Runtime example asset: transparent tile 0 and two player tiles
    .res $0010, $00
    .byte $3C, $7E, $DB, $FF, $FF, $BD, $66, $3C ; tile 1 plane 0
    .byte $00, $24, $24, $00, $00, $42, $18, $00 ; tile 1 plane 1
    .byte $7E, $FF, $A5, $FF, $BD, $C3, $7E, $24 ; tile 2 plane 0
    .byte $00, $5A, $5A, $00, $42, $3C, $00, $18 ; tile 2 plane 1
    .res 8144, $00
