; Generated by nes-pascal for program Procedures
; Mapper 0, 32 KiB PRG-ROM, 8 KiB CHR-ROM

.segment "HEADER"
    .byte "NES", $1A
    .byte 2                  ; PRG-ROM banks, 16 KiB each
    .byte 1                  ; CHR-ROM banks, 8 KiB each
    .byte $00                ; mapper and mirroring flags
    .byte $00                ; mapper upper bits
    .byte $00, $00, $00, $00, $00, $00, $00, $00

.segment "OAM_SHADOW"
; Runtime: page-aligned OAM DMA shadow at $0200-$02FF
runtime_oam_shadow: .res 256 ; $0200: 256-byte page copied to PPU OAM by future sprite runtime support

.segment "RUNTIME_DATA"
; Runtime: no scalar RAM symbols are required in milestone 0.3.1

.segment "TEMPORARIES"
; Compiler: reusable expression and loop storage in regular CPU RAM
expression_temporary_0: .res 1 ; $0300: reusable expression evaluation byte

.segment "USER_VARIABLES"
; Source: variable and parameter declarations in regular CPU RAM
variable_Counter: .res 1 ; $0310: Counter: byte
variable_CallCount: .res 1 ; $0311: CallCount: byte
variable_BackgroundColor: .res 1 ; $0312: BackgroundColor: nes_color

.segment "CODE"

; Interrupt handlers
NMI:
    rti

IRQ:
    rti

; Source: implicit NES runtime initialization
RESET:
    sei
    cld
    ldx #$40
    stx $4017               ; disable frame counter IRQ
    ldx #$FF
    txs
    inx                     ; X = 0
    stx $2000               ; disable NMI
    stx $2001               ; disable rendering
    stx $4010               ; disable DMC IRQ
    bit $2002               ; clear the vblank latch

@wait_vblank_1:
    bit $2002
    bpl @wait_vblank_1

    txa
@clear_ram:
    sta $0000, x
    sta $0100, x
    sta $0200, x
    sta $0300, x
    sta $0400, x
    sta $0500, x
    sta $0600, x
    sta $0700, x
    inx
    bne @clear_ram

@wait_vblank_2:
    bit $2002
    bpl @wait_vblank_2

; Source: BuildState
    jsr procedure_BuildState

; Source: ChooseColor
    jsr procedure_ChooseColor

; Source: nes.set_background_color(value)
    lda #$3F
    sta $2006               ; universal palette address, high byte
    lda #$00
    sta $2006               ; low byte
    lda variable_BackgroundColor
    sta $2007

; Source: nes.run
    lda #$00
    sta $2005               ; scroll X
    sta $2005               ; scroll Y
    lda #$08
    sta $2001               ; enable background rendering

@main_loop:
    jmp @main_loop

; Source: procedure declarations
; Procedure: BuildState
procedure_BuildState:

; Source: InitializeState
    jsr procedure_InitializeState

; Source: AdvanceState
    jsr procedure_AdvanceState
    rts

; Procedure: AdvanceState
procedure_AdvanceState:

; Source: AddStep
    jsr procedure_AddStep

; Source: inc(CallCount)
    inc variable_CallCount
    rts

; Procedure: AddStep
procedure_AddStep:

; Source: inc(Counter, amount)
    lda #$03
    clc
    adc variable_Counter
    sta variable_Counter
    rts

; Procedure: InitializeState
procedure_InitializeState:

; Source: Counter := value
    lda #$00
    sta variable_Counter

; Source: CallCount := value
    lda #$00
    sta variable_CallCount
    rts

; Procedure: ChooseColor
procedure_ChooseColor:

; Source: if condition then
    ; boolean and: evaluate left operand
    ; comparison =: evaluate right operand
    lda #$03
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    beq @comparison_true_7
@comparison_false_8:
    lda #$00              ; false
    jmp @comparison_end_9
@comparison_true_7:
    lda #$01              ; true
@comparison_end_9:
    cmp #$00
    bne @boolean_evaluate_right_3
    jmp @boolean_false_5       ; short-circuit false
@boolean_evaluate_right_3:
    ; evaluate right operand
    ; comparison =: evaluate right operand
    lda #$01
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_CallCount
    cmp expression_temporary_0
    beq @comparison_true_10
@comparison_false_11:
    lda #$00              ; false
    jmp @comparison_end_12
@comparison_true_10:
    lda #$01              ; true
@comparison_end_12:
    cmp #$00
    bne @boolean_true_4
@boolean_false_5:
    lda #$00              ; false
    jmp @boolean_end_6
@boolean_true_4:
    lda #$01              ; true
@boolean_end_6:
    cmp #$00
    bne @if_then_0
    jmp @if_else_2       ; long-branch-safe false path
@if_then_0:

; Source: BackgroundColor := value
    lda #$21
    sta variable_BackgroundColor
    jmp @if_end_1
@if_else_2:

; Source: BackgroundColor := value
    lda #$0F
    sta variable_BackgroundColor
@if_end_1:
    rts

.segment "VECTORS"
    .word NMI
    .word RESET
    .word IRQ

.segment "CHR"
    .res 8192, $00          ; empty CHR-ROM
