; Generated by nes-pascal for program ProcedureParameters
; Mapper 0, 32 KiB PRG-ROM, 8 KiB CHR-ROM

.segment "HEADER"
    .byte "NES", $1A
    .byte 2                  ; PRG-ROM banks, 16 KiB each
    .byte 1                  ; CHR-ROM banks, 8 KiB each
    .byte $00                ; mapper and mirroring flags
    .byte $00                ; mapper upper bits
    .byte $00, $00, $00, $00, $00, $00, $00, $00

.segment "ZERO_PAGE_RUNTIME": zeropage
; Runtime: frame synchronization state, isolated from compiler temporaries
runtime_frame_counter: .res 1 ; $0000: volatile 8-bit counter incremented once by each NMI
runtime_frame_ready: .res 1 ; $0001: advisory frame-ready signal consumed by main frame waits
runtime_last_processed_frame: .res 1 ; $0002: persistent update-loop frame baseline
runtime_controller_1_current: .res 1 ; $0003: controller 1 state for the newest processed frame
runtime_controller_1_previous: .res 1 ; $0004: controller 1 state for the preceding processed frame
runtime_controller_2_current: .res 1 ; $0005: controller 2 state for the newest processed frame
runtime_controller_2_previous: .res 1 ; $0006: controller 2 state for the preceding processed frame
runtime_controller_polled_frame: .res 1 ; $0007: frame counter value of the most recent controller poll
runtime_controller_poll_valid: .res 1 ; $0008: distinguishes an initial zero byte from a completed frame-zero poll

.segment "ZERO_PAGE_TEMPORARIES": zeropage
; Compiler: mandatory expression and loop storage in Zero Page
expression_temporary_0: .res 1 ; $0010: reusable expression evaluation byte

.segment "ZERO_PAGE_VARIABLES": zeropage
; Source: optional global-variable promotion with regular-RAM fallback
variable_Counter: .res 1 ; $0080: Counter: byte
variable_BackgroundColor: .res 1 ; $0081: BackgroundColor: nes_color


.segment "RUNTIME_DATA"
; Runtime: regular-RAM state kept separate from user variables
runtime_ppuctrl_shadow: .res 1 ; $0200: authoritative PPUCTRL value restored each NMI
runtime_ppumask_shadow: .res 1 ; $0201: authoritative PPUMASK value restored each NMI
runtime_scroll_x_shadow: .res 1 ; $0202: authoritative horizontal scroll restored each NMI
runtime_scroll_y_shadow: .res 1 ; $0203: authoritative vertical scroll restored each NMI

.segment "USER_VARIABLES"
; Source: non-promoted variables and all parameters in regular CPU RAM
variable_Enabled: .res 1 ; $0204: Enabled: boolean
parameter_Initialize_Start: .res 1 ; $0205: Initialize.Start: byte
parameter_Initialize_Step: .res 1 ; $0206: Initialize.Step: byte
parameter_Initialize_EnabledValue: .res 1 ; $0207: Initialize.EnabledValue: boolean
parameter_ApplyStep_Amount: .res 1 ; $0208: ApplyStep.Amount: byte
parameter_ApplyStep_ShouldApply: .res 1 ; $0209: ApplyStep.ShouldApply: boolean
parameter_SelectColor_Matches: .res 1 ; $020A: SelectColor.Matches: boolean

.segment "CODE"

; Interrupt handlers
NMI:
    pha
    txa
    pha
    tya
    pha

    inc runtime_frame_counter ; volatile 8-bit counter, wraps modulo 256
    lda #$01
    sta runtime_frame_ready   ; advisory; frame counter is authoritative

    ; Runtime: authoritative final PPU state after all VBlank work
    bit $2002               ; reset the shared PPU write latch
    lda runtime_ppuctrl_shadow
    sta $2000
    lda runtime_scroll_x_shadow
    sta $2005               ; scroll X (first write)
    lda runtime_scroll_y_shadow
    sta $2005               ; scroll Y (second write)
    lda runtime_ppumask_shadow
    sta $2001

    pla
    tay
    pla
    tax
    pla
    rti

IRQ:
    rti

; Source: implicit NES runtime initialization
RESET:
    sei
    cld
    ldx #$40
    stx $4017               ; disable frame counter IRQ
    ldx #$FF
    txs
    inx                     ; X = 0
    stx $2000               ; disable NMI
    stx $2001               ; disable rendering
    stx $4010               ; disable DMC IRQ
    bit $2002               ; clear the vblank latch

@wait_vblank_1:
    bit $2002
    bpl @wait_vblank_1

    txa
@clear_ram:
    sta $0000, x
    sta $0100, x
    sta $0200, x
    sta $0300, x
    sta $0400, x
    sta $0500, x
    sta $0600, x
    sta $0700, x
    inx
    bne @clear_ram

@wait_vblank_2:
    bit $2002
    bpl @wait_vblank_2

; Source: Initialize
    ; argument 1: Start
    lda #$02
    sta parameter_Initialize_Start
    ; argument 2: Step
    lda #$03
    sta parameter_Initialize_Step
    ; argument 3: EnabledValue
    lda #$01              ; true
    sta parameter_Initialize_EnabledValue
    jsr procedure_Initialize

; Source: SelectColor
    ; argument 1: Matches
    ; boolean and: evaluate left operand
    lda variable_Enabled
    cmp #$00
    bne @boolean_evaluate_right_0
    jmp @boolean_false_2       ; short-circuit false
@boolean_evaluate_right_0:
    ; evaluate right operand
    ; comparison =: evaluate right operand
    lda #$06
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    beq @comparison_true_4
@comparison_false_5:
    lda #$00              ; false
    jmp @comparison_end_6
@comparison_true_4:
    lda #$01              ; true
@comparison_end_6:
    cmp #$00
    bne @boolean_true_1
@boolean_false_2:
    lda #$00              ; false
    jmp @boolean_end_3
@boolean_true_1:
    lda #$01              ; true
@boolean_end_3:
    sta parameter_SelectColor_Matches
    jsr procedure_SelectColor

; Source: nes.set_background_color(value)
    lda #$3F
    sta $2006               ; universal palette address, high byte
    lda #$00
    sta $2006               ; low byte
    lda variable_BackgroundColor
    sta $2007

; Source: nes.run
; Runtime: defer rendering-sensitive setup to VBlank
@wait_render_vblank_7:
    bit $2002
    bpl @wait_render_vblank_7
    lda runtime_ppuctrl_shadow
    ora #$80
    sta runtime_ppuctrl_shadow ; preserve bits and enable NMI
    sta $2000
    lda runtime_scroll_x_shadow ; zero-filled default scroll X
    sta $2005
    lda runtime_scroll_y_shadow ; zero-filled default scroll Y
    sta $2005
    lda runtime_ppumask_shadow
    ora #$1E
    sta runtime_ppumask_shadow ; preserve bits and enable rendering
    sta $2001

; Runtime: implicit stable loop after the main program finishes
@runtime_idle_loop:
    jmp @runtime_idle_loop

; Runtime: idempotent controller update for one newly processed frame
runtime_update_controllers:
    tax                     ; X keeps the caller's accepted frame value
    lda runtime_controller_poll_valid
    beq @controllers_need_poll
    txa
    cmp runtime_controller_polled_frame
    beq @controllers_already_current
@controllers_need_poll:
    lda #$01
    sta runtime_controller_poll_valid
    txa
    sta runtime_controller_polled_frame
    lda runtime_controller_1_current
    sta runtime_controller_1_previous
    lda runtime_controller_2_current
    sta runtime_controller_2_previous
    jsr runtime_read_controller_ports
@controllers_already_current:
    rts

; Runtime: isolated standard NES serial controller protocol
; Bit layout: A, B, Select, Start, Up, Down, Left, Right = bits 0..7.
runtime_read_controller_ports:
    lda #$01
    sta $4016               ; latch both controllers
    lda #$00
    sta $4016               ; begin serial reads
    sta runtime_controller_1_current
    sta runtime_controller_2_current
    ldx #$08
@read_controller_bits:
    lda $4016
    lsr a                   ; controller 1 serial bit -> carry
    ror runtime_controller_1_current
    lda $4017
    lsr a                   ; controller 2 serial bit -> carry
    ror runtime_controller_2_current
    dex
    bne @read_controller_bits
    rts


; Source: procedure declarations
; Procedure: Initialize
procedure_Initialize:

; Source: Counter := value
    lda parameter_Initialize_Start
    sta variable_Counter

; Source: Enabled := value
    lda parameter_Initialize_EnabledValue
    sta variable_Enabled

; Source: Step := value
    ; binary +: evaluate right operand
    lda #$01
    sta expression_temporary_0
    ; evaluate left operand
    lda parameter_Initialize_Step
    clc
    adc expression_temporary_0
    sta parameter_Initialize_Step

; Source: ApplyStep
    ; argument 1: Amount
    lda parameter_Initialize_Step
    sta parameter_ApplyStep_Amount
    ; argument 2: ShouldApply
    lda parameter_Initialize_EnabledValue
    sta parameter_ApplyStep_ShouldApply
    jsr procedure_ApplyStep
    rts

; Procedure: ApplyStep
procedure_ApplyStep:

; Source: if condition then
    lda parameter_ApplyStep_ShouldApply
    cmp #$00
    bne @if_then_8
    jmp @if_end_9       ; long-branch-safe false path
@if_then_8:

; Source: inc(Counter, amount)
    lda parameter_ApplyStep_Amount
    clc
    adc variable_Counter
    sta variable_Counter
@if_end_9:
    rts

; Procedure: SelectColor
procedure_SelectColor:

; Source: if condition then
    lda parameter_SelectColor_Matches
    cmp #$00
    bne @if_then_10
    jmp @if_else_12       ; long-branch-safe false path
@if_then_10:

; Source: BackgroundColor := value
    lda #$21
    sta variable_BackgroundColor
    jmp @if_end_11
@if_else_12:

; Source: BackgroundColor := value
    lda #$0F
    sta variable_BackgroundColor
@if_end_11:
    rts

.segment "VECTORS"
    .word NMI
    .word RESET
    .word IRQ

.segment "CHR"
    .res 8192, $00          ; empty CHR-ROM
