; Generated by nes-pascal for program ProcedureParameters
; Mapper 0, 32 KiB PRG-ROM, 8 KiB CHR-ROM

.segment "HEADER"
    .byte "NES", $1A
    .byte 2                  ; PRG-ROM banks, 16 KiB each
    .byte 1                  ; CHR-ROM banks, 8 KiB each
    .byte $00                ; mapper and mirroring flags
    .byte $00                ; mapper upper bits
    .byte $00, $00, $00, $00, $00, $00, $00, $00

.segment "ZERO_PAGE_RUNTIME": zeropage
; Runtime: frame synchronization state, isolated from compiler temporaries
runtime_frame_counter: .res 1 ; $0000: volatile 8-bit counter incremented once by each NMI
runtime_frame_ready: .res 1 ; $0001: advisory frame-ready signal consumed by main frame waits
runtime_last_processed_frame: .res 1 ; $0002: persistent update-loop frame baseline

.segment "ZERO_PAGE_TEMPORARIES": zeropage
; Compiler: mandatory expression and loop storage in Zero Page
expression_temporary_0: .res 1 ; $0010: reusable expression evaluation byte

.segment "ZERO_PAGE_VARIABLES": zeropage
; Source: optional global-variable promotion with regular-RAM fallback
variable_Counter: .res 1 ; $0080: Counter: byte
variable_BackgroundColor: .res 1 ; $0081: BackgroundColor: nes_color

.segment "OAM_SHADOW"
; Runtime: page-aligned OAM DMA shadow at $0200-$02FF
runtime_oam_shadow: .res 256 ; $0200: 256-byte page copied to PPU OAM by future sprite runtime support

.segment "RUNTIME_DATA"
; Runtime: no scalar regular-RAM symbols are currently required

.segment "USER_VARIABLES"
; Source: non-promoted variables and all parameters in regular CPU RAM
variable_Enabled: .res 1 ; $0300: Enabled: boolean
parameter_Initialize_Start: .res 1 ; $0301: Initialize.Start: byte
parameter_Initialize_Step: .res 1 ; $0302: Initialize.Step: byte
parameter_Initialize_EnabledValue: .res 1 ; $0303: Initialize.EnabledValue: boolean
parameter_ApplyStep_Amount: .res 1 ; $0304: ApplyStep.Amount: byte
parameter_ApplyStep_ShouldApply: .res 1 ; $0305: ApplyStep.ShouldApply: boolean
parameter_SelectColor_Matches: .res 1 ; $0306: SelectColor.Matches: boolean

.segment "CODE"

; Interrupt handlers
NMI:
    pha
    txa
    pha
    tya
    pha

    inc runtime_frame_counter ; volatile 8-bit counter, wraps modulo 256
    lda #$01
    sta runtime_frame_ready   ; advisory; frame counter is authoritative

    pla
    tay
    pla
    tax
    pla
    rti

IRQ:
    rti

; Source: implicit NES runtime initialization
RESET:
    sei
    cld
    ldx #$40
    stx $4017               ; disable frame counter IRQ
    ldx #$FF
    txs
    inx                     ; X = 0
    stx $2000               ; disable NMI
    stx $2001               ; disable rendering
    stx $4010               ; disable DMC IRQ
    bit $2002               ; clear the vblank latch

@wait_vblank_1:
    bit $2002
    bpl @wait_vblank_1

    txa
@clear_ram:
    sta $0000, x
    sta $0100, x
    sta $0200, x
    sta $0300, x
    sta $0400, x
    sta $0500, x
    sta $0600, x
    sta $0700, x
    inx
    bne @clear_ram

@wait_vblank_2:
    bit $2002
    bpl @wait_vblank_2

; Source: Initialize
    ; argument 1: Start
    lda #$02
    sta parameter_Initialize_Start
    ; argument 2: Step
    lda #$03
    sta parameter_Initialize_Step
    ; argument 3: EnabledValue
    lda #$01              ; true
    sta parameter_Initialize_EnabledValue
    jsr procedure_Initialize

; Source: SelectColor
    ; argument 1: Matches
    ; boolean and: evaluate left operand
    lda variable_Enabled
    cmp #$00
    bne @boolean_evaluate_right_0
    jmp @boolean_false_2       ; short-circuit false
@boolean_evaluate_right_0:
    ; evaluate right operand
    ; comparison =: evaluate right operand
    lda #$06
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    beq @comparison_true_4
@comparison_false_5:
    lda #$00              ; false
    jmp @comparison_end_6
@comparison_true_4:
    lda #$01              ; true
@comparison_end_6:
    cmp #$00
    bne @boolean_true_1
@boolean_false_2:
    lda #$00              ; false
    jmp @boolean_end_3
@boolean_true_1:
    lda #$01              ; true
@boolean_end_3:
    sta parameter_SelectColor_Matches
    jsr procedure_SelectColor

; Source: nes.set_background_color(value)
    lda #$3F
    sta $2006               ; universal palette address, high byte
    lda #$00
    sta $2006               ; low byte
    lda variable_BackgroundColor
    sta $2007

; Source: nes.run
; Runtime: defer rendering-sensitive setup to VBlank
@wait_render_vblank_7:
    bit $2002
    bpl @wait_render_vblank_7
    lda #$00
    sta $2005               ; scroll X
    sta $2005               ; scroll Y
    lda #$80
    sta $2000               ; enable NMI after initialization
    lda #$08
    sta $2001               ; enable background rendering

; Runtime: implicit stable loop after the main program finishes
@runtime_idle_loop:
    jmp @runtime_idle_loop


; Source: procedure declarations
; Procedure: Initialize
procedure_Initialize:

; Source: Counter := value
    lda parameter_Initialize_Start
    sta variable_Counter

; Source: Enabled := value
    lda parameter_Initialize_EnabledValue
    sta variable_Enabled

; Source: Step := value
    ; binary +: evaluate right operand
    lda #$01
    sta expression_temporary_0
    ; evaluate left operand
    lda parameter_Initialize_Step
    clc
    adc expression_temporary_0
    sta parameter_Initialize_Step

; Source: ApplyStep
    ; argument 1: Amount
    lda parameter_Initialize_Step
    sta parameter_ApplyStep_Amount
    ; argument 2: ShouldApply
    lda parameter_Initialize_EnabledValue
    sta parameter_ApplyStep_ShouldApply
    jsr procedure_ApplyStep
    rts

; Procedure: ApplyStep
procedure_ApplyStep:

; Source: if condition then
    lda parameter_ApplyStep_ShouldApply
    cmp #$00
    bne @if_then_8
    jmp @if_end_9       ; long-branch-safe false path
@if_then_8:

; Source: inc(Counter, amount)
    lda parameter_ApplyStep_Amount
    clc
    adc variable_Counter
    sta variable_Counter
@if_end_9:
    rts

; Procedure: SelectColor
procedure_SelectColor:

; Source: if condition then
    lda parameter_SelectColor_Matches
    cmp #$00
    bne @if_then_10
    jmp @if_else_12       ; long-branch-safe false path
@if_then_10:

; Source: BackgroundColor := value
    lda #$21
    sta variable_BackgroundColor
    jmp @if_end_11
@if_else_12:

; Source: BackgroundColor := value
    lda #$0F
    sta variable_BackgroundColor
@if_end_11:
    rts

.segment "VECTORS"
    .word NMI
    .word RESET
    .word IRQ

.segment "CHR"
    .res 8192, $00          ; empty CHR-ROM
