; Generated by nes-pascal for program Procedures
; Mapper 0, 32 KiB PRG-ROM, 8 KiB CHR-ROM

.segment "HEADER"
    .byte "NES", $1A
    .byte 2                  ; PRG-ROM banks, 16 KiB each
    .byte 1                  ; CHR-ROM banks, 8 KiB each
    .byte $00                ; mapper and mirroring flags
    .byte $00                ; mapper upper bits
    .byte $00, $00, $00, $00, $00, $00, $00, $00

.segment "ZERO_PAGE_RUNTIME": zeropage
; Runtime: frame synchronization state, isolated from compiler temporaries
runtime_frame_counter: .res 1 ; $0000: volatile 8-bit counter incremented once by each NMI
runtime_frame_ready: .res 1 ; $0001: advisory frame-ready signal consumed by main frame waits
runtime_last_processed_frame: .res 1 ; $0002: persistent update-loop frame baseline
runtime_controller_1_current: .res 1 ; $0003: controller 1 state for the newest processed frame
runtime_controller_1_previous: .res 1 ; $0004: controller 1 state for the preceding processed frame
runtime_controller_2_current: .res 1 ; $0005: controller 2 state for the newest processed frame
runtime_controller_2_previous: .res 1 ; $0006: controller 2 state for the preceding processed frame
runtime_controller_polled_frame: .res 1 ; $0007: frame counter value of the most recent controller poll
runtime_controller_poll_valid: .res 1 ; $0008: distinguishes an initial zero byte from a completed frame-zero poll

.segment "ZERO_PAGE_TEMPORARIES": zeropage
; Compiler: mandatory expression and loop storage in Zero Page
expression_temporary_0: .res 1 ; $0010: reusable expression evaluation byte

.segment "ZERO_PAGE_VARIABLES": zeropage
; Source: optional global-variable promotion with regular-RAM fallback
variable_Counter: .res 1 ; $0080: Counter: byte
variable_CallCount: .res 1 ; $0081: CallCount: byte
variable_BackgroundColor: .res 1 ; $0082: BackgroundColor: nes_color

.segment "OAM_SHADOW"
; Runtime: page-aligned OAM DMA shadow at $0200-$02FF
runtime_oam_shadow: .res 256 ; $0200: 256-byte page copied to PPU OAM by runtime sprite support

.segment "RUNTIME_DATA"
; Runtime: regular-RAM state kept separate from user variables
    ; no scalar regular-RAM runtime symbols required

.segment "USER_VARIABLES"
; Source: non-promoted variables and all parameters in regular CPU RAM
    ; no user variables

.segment "CODE"

; Interrupt handlers
NMI:
    pha
    txa
    pha
    tya
    pha

    inc runtime_frame_counter ; volatile 8-bit counter, wraps modulo 256
    lda #$01
    sta runtime_frame_ready   ; advisory; frame counter is authoritative

    pla
    tay
    pla
    tax
    pla
    rti

IRQ:
    rti

; Source: implicit NES runtime initialization
RESET:
    sei
    cld
    ldx #$40
    stx $4017               ; disable frame counter IRQ
    ldx #$FF
    txs
    inx                     ; X = 0
    stx $2000               ; disable NMI
    stx $2001               ; disable rendering
    stx $4010               ; disable DMC IRQ
    bit $2002               ; clear the vblank latch

@wait_vblank_1:
    bit $2002
    bpl @wait_vblank_1

    txa
@clear_ram:
    sta $0000, x
    sta $0100, x
    sta $0200, x
    sta $0300, x
    sta $0400, x
    sta $0500, x
    sta $0600, x
    sta $0700, x
    inx
    bne @clear_ram

@wait_vblank_2:
    bit $2002
    bpl @wait_vblank_2

; Source: BuildState
    jsr procedure_BuildState

; Source: ChooseColor
    jsr procedure_ChooseColor

; Source: nes.set_background_color(value)
    lda #$3F
    sta $2006               ; universal palette address, high byte
    lda #$00
    sta $2006               ; low byte
    lda variable_BackgroundColor
    sta $2007

; Source: nes.run
; Runtime: defer rendering-sensitive setup to VBlank
@wait_render_vblank_0:
    bit $2002
    bpl @wait_render_vblank_0
    lda #$00
    sta $2005               ; scroll X
    sta $2005               ; scroll Y
    lda #$80
    sta $2000               ; enable NMI after initialization
    lda #$08
    sta $2001               ; enable selected rendering layers

; Runtime: implicit stable loop after the main program finishes
@runtime_idle_loop:
    jmp @runtime_idle_loop

; Runtime: idempotent controller update for one newly processed frame
runtime_update_controllers:
    tax                     ; X keeps the caller's accepted frame value
    lda runtime_controller_poll_valid
    beq @controllers_need_poll
    txa
    cmp runtime_controller_polled_frame
    beq @controllers_already_current
@controllers_need_poll:
    lda #$01
    sta runtime_controller_poll_valid
    txa
    sta runtime_controller_polled_frame
    lda runtime_controller_1_current
    sta runtime_controller_1_previous
    lda runtime_controller_2_current
    sta runtime_controller_2_previous
    jsr runtime_read_controller_ports
@controllers_already_current:
    rts

; Runtime: isolated standard NES serial controller protocol
; Bit layout: A, B, Select, Start, Up, Down, Left, Right = bits 0..7.
runtime_read_controller_ports:
    lda #$01
    sta $4016               ; latch both controllers
    lda #$00
    sta $4016               ; begin serial reads
    sta runtime_controller_1_current
    sta runtime_controller_2_current
    ldx #$08
@read_controller_bits:
    lda $4016
    lsr a                   ; controller 1 serial bit -> carry
    ror runtime_controller_1_current
    lda $4017
    lsr a                   ; controller 2 serial bit -> carry
    ror runtime_controller_2_current
    dex
    bne @read_controller_bits
    rts


; Source: procedure declarations
; Procedure: BuildState
procedure_BuildState:

; Source: InitializeState
    jsr procedure_InitializeState

; Source: AdvanceState
    jsr procedure_AdvanceState
    rts

; Procedure: AdvanceState
procedure_AdvanceState:

; Source: AddStep
    jsr procedure_AddStep

; Source: inc(CallCount)
    inc variable_CallCount
    rts

; Procedure: AddStep
procedure_AddStep:

; Source: inc(Counter, amount)
    lda #$03
    clc
    adc variable_Counter
    sta variable_Counter
    rts

; Procedure: InitializeState
procedure_InitializeState:

; Source: Counter := value
    lda #$00
    sta variable_Counter

; Source: CallCount := value
    lda #$00
    sta variable_CallCount
    rts

; Procedure: ChooseColor
procedure_ChooseColor:

; Source: if condition then
    ; boolean and: evaluate left operand
    ; comparison =: evaluate right operand
    lda #$03
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_Counter
    cmp expression_temporary_0
    beq @comparison_true_8
@comparison_false_9:
    lda #$00              ; false
    jmp @comparison_end_10
@comparison_true_8:
    lda #$01              ; true
@comparison_end_10:
    cmp #$00
    bne @boolean_evaluate_right_4
    jmp @boolean_false_6       ; short-circuit false
@boolean_evaluate_right_4:
    ; evaluate right operand
    ; comparison =: evaluate right operand
    lda #$01
    sta expression_temporary_0
    ; evaluate left operand
    lda variable_CallCount
    cmp expression_temporary_0
    beq @comparison_true_11
@comparison_false_12:
    lda #$00              ; false
    jmp @comparison_end_13
@comparison_true_11:
    lda #$01              ; true
@comparison_end_13:
    cmp #$00
    bne @boolean_true_5
@boolean_false_6:
    lda #$00              ; false
    jmp @boolean_end_7
@boolean_true_5:
    lda #$01              ; true
@boolean_end_7:
    cmp #$00
    bne @if_then_1
    jmp @if_else_3       ; long-branch-safe false path
@if_then_1:

; Source: BackgroundColor := value
    lda #$21
    sta variable_BackgroundColor
    jmp @if_end_2
@if_else_3:

; Source: BackgroundColor := value
    lda #$0F
    sta variable_BackgroundColor
@if_end_2:
    rts

.segment "VECTORS"
    .word NMI
    .word RESET
    .word IRQ

.segment "CHR"
    .res 8192, $00          ; empty CHR-ROM
