"""ca65 Assembly generation for an NROM-256 image."""

from .ast import (
    BinaryOperator,
    BooleanOperator,
    BuiltInType,
    ComparisonOperator,
    ForDirection,
    ImmediateValue,
    ResolvedAssignment,
    ResolvedBinaryExpression,
    ResolvedBooleanBinaryExpression,
    ResolvedBooleanNotExpression,
    ResolvedBreakStatement,
    ResolvedComparisonExpression,
    ResolvedContinueStatement,
    ResolvedDecrementStatement,
    ResolvedForStatement,
    ResolvedIfStatement,
    ResolvedIncrementStatement,
    ResolvedProgram,
    ResolvedProcedure,
    ResolvedProcedureCall,
    ResolvedRepeatStatement,
    ResolvedSetBackgroundColor,
    ResolvedStatement,
    ResolvedUnaryExpression,
    ResolvedValue,
    ResolvedWhileStatement,
    Run,
    UnaryOperator,
    VariableValue,
)


def generate(program: ResolvedProgram) -> str:
    color_commands = [
        statement
        for statement in program.statements
        if isinstance(statement, ResolvedSetBackgroundColor)
    ]
    run_commands = [
        statement for statement in program.statements if isinstance(statement, Run)
    ]
    if len(color_commands) != 1 or len(run_commands) != 1:
        raise ValueError("invalid resolved AST for the current milestone")

    variable_lines = [
        f"{variable.label}: .res 1       ; {variable.name}: {variable.type.value}"
        for variable in program.variables
    ]
    all_statements = [
        *program.statements,
        *(
            statement
            for procedure in program.procedures
            for statement in procedure.body
        ),
    ]
    temporary_count = max(
        (
            _statement_expression_depth(statement)
            for statement in all_statements
        ),
        default=0,
    )
    variable_lines.extend(
        f"expression_temporary_{index}: .res 1 ; expression temporary"
        for index in range(temporary_count)
    )
    for_temporary_count = sum(
        _count_for_statements(statement)
        for statement in all_statements
    )
    variable_lines.extend(
        f"for_limit_{index}: .res 1        ; cached for-loop final value"
        for index in range(for_temporary_count)
    )
    if not variable_lines:
        variable_lines.append("    ; no variables")

    label_counter = [0]
    for_counter = [0]
    statement_lines = _generate_statements(
        program.statements,
        label_counter,
        (),
        for_counter,
    )
    procedure_lines = _generate_procedures(
        program.procedures,
        label_counter,
        for_counter,
    )

    variables = "\n".join(variable_lines)
    statements = "\n".join(statement_lines)
    procedures = (
        "\n\n; Source: procedure declarations\n"
        + "\n".join(procedure_lines)
        if procedure_lines
        else ""
    )
    return f"""; Generated by nes-pascal for program {program.name}
; Mapper 0, 32 KiB PRG-ROM, 8 KiB CHR-ROM

.segment "HEADER"
    .byte "NES", $1A
    .byte 2                  ; 2 x 16 KiB PRG-ROM
    .byte 1                  ; 1 x 8 KiB CHR-ROM
    .byte $00                ; mapper 0, horizontal mirroring
    .byte $00                ; mapper 0
    .byte $00, $00, $00, $00, $00, $00, $00, $00

.segment "BSS"
; Source: variable declarations in regular CPU RAM
{variables}

.segment "CODE"

; Interrupt handlers
NMI:
    rti

IRQ:
    rti

; Source: implicit NES runtime initialization
RESET:
    sei
    cld
    ldx #$40
    stx $4017               ; disable frame counter IRQ
    ldx #$FF
    txs
    inx                     ; X = 0
    stx $2000               ; disable NMI
    stx $2001               ; disable rendering
    stx $4010               ; disable DMC IRQ
    bit $2002               ; clear the vblank latch

@wait_vblank_1:
    bit $2002
    bpl @wait_vblank_1

    txa
@clear_ram:
    sta $0000, x
    sta $0100, x
    sta $0200, x
    sta $0300, x
    sta $0400, x
    sta $0500, x
    sta $0600, x
    sta $0700, x
    inx
    bne @clear_ram

@wait_vblank_2:
    bit $2002
    bpl @wait_vblank_2
{statements}{procedures}

.segment "VECTORS"
    .word NMI
    .word RESET
    .word IRQ

.segment "CHR"
    .res 8192, $00          ; empty CHR-ROM
"""


def _generate_statements(
    statements: tuple[ResolvedStatement, ...],
    label_counter: list[int],
    loop_targets: tuple[tuple[str, str], ...],
    for_counter: list[int],
) -> list[str]:
    statement_lines: list[str] = []
    for statement in statements:
        if isinstance(statement, ResolvedAssignment):
            statement_lines.extend(
                [
                    "",
                    f"; Source: {statement.target.name} := value",
                    *_load_value(statement.value, label_counter),
                    f"    sta {statement.target.label}",
                ]
            )
        elif isinstance(statement, ResolvedSetBackgroundColor):
            statement_lines.extend(
                [
                    "",
                    "; Source: nes.set_background_color(value)",
                    "    lda #$3F",
                    "    sta $2006               ; universal palette address, high byte",
                    "    lda #$00",
                    "    sta $2006               ; low byte",
                    *_load_value(statement.argument, label_counter),
                    "    sta $2007",
                ]
            )
        elif isinstance(statement, Run):
            statement_lines.extend(
                [
                    "",
                    "; Source: nes.run",
                    "    lda #$00",
                    "    sta $2005               ; scroll X",
                    "    sta $2005               ; scroll Y",
                    "    lda #$08",
                    "    sta $2001               ; enable background rendering",
                    "",
                    "@main_loop:",
                    "    jmp @main_loop",
                ]
            )
        elif isinstance(statement, ResolvedIfStatement):
            then_label = _new_label(label_counter, "if_then")
            end_label = _new_label(label_counter, "if_end")
            else_label = (
                _new_label(label_counter, "if_else")
                if statement.else_branch is not None
                else end_label
            )
            statement_lines.extend(
                [
                    "",
                    "; Source: if condition then",
                    *_load_value(statement.condition, label_counter),
                    "    cmp #$00",
                    f"    bne {then_label}",
                    f"    jmp {else_label}       ; long-branch-safe false path",
                    f"{then_label}:",
                    *_generate_statements(
                        statement.then_branch,
                        label_counter,
                        loop_targets,
                        for_counter,
                    ),
                ]
            )
            if statement.else_branch is not None:
                statement_lines.extend(
                    [
                        f"    jmp {end_label}",
                        f"{else_label}:",
                        *_generate_statements(
                            statement.else_branch,
                            label_counter,
                            loop_targets,
                            for_counter,
                        ),
                    ]
                )
            statement_lines.append(f"{end_label}:")
        elif isinstance(statement, ResolvedWhileStatement):
            condition_label = _new_label(label_counter, "while_condition")
            body_label = _new_label(label_counter, "while_body")
            end_label = _new_label(label_counter, "while_end")
            statement_lines.extend(
                [
                    "",
                    "; Source: while condition do",
                    f"{condition_label}:",
                    *_load_value(statement.condition, label_counter),
                    "    cmp #$00",
                    f"    bne {body_label}",
                    f"    jmp {end_label}       ; long-branch-safe loop exit",
                    f"{body_label}:",
                    *_generate_statements(
                        statement.body,
                        label_counter,
                        (*loop_targets, (end_label, condition_label)),
                        for_counter,
                    ),
                    f"    jmp {condition_label}",
                    f"{end_label}:",
                ]
            )
        elif isinstance(statement, ResolvedRepeatStatement):
            body_label = _new_label(label_counter, "repeat_body")
            condition_label = _new_label(label_counter, "repeat_condition")
            end_label = _new_label(label_counter, "repeat_end")
            statement_lines.extend(
                [
                    "",
                    "; Source: repeat until condition",
                    f"{body_label}:",
                    *_generate_statements(
                        statement.body,
                        label_counter,
                        (*loop_targets, (end_label, condition_label)),
                        for_counter,
                    ),
                    f"{condition_label}:",
                    *_load_value(statement.condition, label_counter),
                    "    cmp #$00",
                    f"    bne {end_label}",
                    f"    jmp {body_label}       ; long-branch-safe repeat",
                    f"{end_label}:",
                ]
            )
        elif isinstance(statement, ResolvedIncrementStatement):
            statement_lines.extend(
                _generate_increment(statement, label_counter)
            )
        elif isinstance(statement, ResolvedDecrementStatement):
            statement_lines.extend(
                _generate_decrement(statement, label_counter)
            )
        elif isinstance(statement, ResolvedForStatement):
            for_index = for_counter[0]
            for_counter[0] += 1
            limit_temporary = f"for_limit_{for_index}"
            condition_label = _new_label(label_counter, "for_condition")
            body_label = _new_label(label_counter, "for_body")
            step_label = _new_label(label_counter, "for_step")
            end_label = _new_label(label_counter, "for_end")
            condition_branches = (
                [
                    f"    bcc {body_label}",
                    f"    beq {body_label}",
                ]
                if statement.direction is ForDirection.TO
                else [f"    bcs {body_label}"]
            )
            step_instruction = (
                f"    inc {statement.target.label}"
                if statement.direction is ForDirection.TO
                else f"    dec {statement.target.label}"
            )
            statement_lines.extend(
                [
                    "",
                    f"; Source: for variable := initial "
                    f"{statement.direction.value} final do",
                    *_load_value(statement.initial, label_counter),
                    f"    sta {statement.target.label}",
                    *_load_value(statement.final, label_counter),
                    f"    sta {limit_temporary}   ; evaluate final value once",
                    f"{condition_label}:",
                    f"    lda {statement.target.label}",
                    f"    cmp {limit_temporary}",
                    *condition_branches,
                    f"    jmp {end_label}       ; long-branch-safe loop exit",
                    f"{body_label}:",
                    *_generate_statements(
                        statement.body,
                        label_counter,
                        (*loop_targets, (end_label, step_label)),
                        for_counter,
                    ),
                    f"{step_label}:",
                    f"    lda {statement.target.label}",
                    f"    cmp {limit_temporary}",
                    f"    beq {end_label}        ; stop before byte wraparound",
                    step_instruction,
                    f"    jmp {condition_label}",
                    f"{end_label}:",
                ]
            )
        elif isinstance(statement, ResolvedProcedureCall):
            statement_lines.extend(
                [
                    "",
                    f"; Source: {statement.name}",
                    f"    jsr {statement.label}",
                ]
            )
        elif isinstance(statement, ResolvedBreakStatement):
            assert loop_targets
            break_label, _ = loop_targets[-1]
            statement_lines.extend(
                [
                    "",
                    "; Source: break",
                    f"    jmp {break_label}",
                ]
            )
        else:
            assert isinstance(statement, ResolvedContinueStatement)
            assert loop_targets
            _, continue_label = loop_targets[-1]
            statement_lines.extend(
                [
                    "",
                    "; Source: continue",
                    f"    jmp {continue_label}",
                ]
            )

    return statement_lines


def _generate_procedures(
    procedures: tuple[ResolvedProcedure, ...],
    label_counter: list[int],
    for_counter: list[int],
) -> list[str]:
    lines: list[str] = []
    for procedure in procedures:
        if lines:
            lines.append("")
        lines.extend(
            [
                f"; Procedure: {procedure.name}",
                f"{procedure.label}:",
                *_generate_statements(
                    procedure.body,
                    label_counter,
                    (),
                    for_counter,
                ),
                "    rts",
            ]
        )
    return lines


def _generate_increment(
    statement: ResolvedIncrementStatement,
    label_counter: list[int],
) -> list[str]:
    if statement.amount is None:
        return [
            "",
            f"; Source: inc({statement.target.name})",
            f"    inc {statement.target.label}",
        ]
    return [
        "",
        f"; Source: inc({statement.target.name}, amount)",
        *_load_value(statement.amount, label_counter),
        "    clc",
        f"    adc {statement.target.label}",
        f"    sta {statement.target.label}",
    ]


def _generate_decrement(
    statement: ResolvedDecrementStatement,
    label_counter: list[int],
) -> list[str]:
    if statement.amount is None:
        return [
            "",
            f"; Source: dec({statement.target.name})",
            f"    dec {statement.target.label}",
        ]
    return [
        "",
        f"; Source: dec({statement.target.name}, amount)",
        *_load_value(statement.amount, label_counter),
        "    sta expression_temporary_0",
        f"    lda {statement.target.label}",
        "    sec",
        "    sbc expression_temporary_0",
        f"    sta {statement.target.label}",
    ]


def _load_value(value: ResolvedValue, label_counter: list[int]) -> list[str]:
    if isinstance(value, ImmediateValue):
        if value.type is BuiltInType.BOOLEAN:
            description = "true" if value.value else "false"
            return [f"    lda #${value.value:02X}              ; {description}"]
        return [f"    lda #${value.value:02X}"]
    if isinstance(value, VariableValue):
        return [f"    lda {value.variable.label}"]
    if isinstance(value, ResolvedUnaryExpression):
        lines = _load_value(value.operand, label_counter)
        if value.operator is UnaryOperator.PLUS:
            return [*lines, "    ; unary + leaves the byte unchanged"]
        return [
            *lines,
            "    eor #$FF                ; unary -: two's complement",
            "    clc",
            "    adc #$01",
        ]

    if isinstance(value, ResolvedBinaryExpression):
        return _load_binary_expression(value, 0, label_counter)
    if isinstance(value, ResolvedComparisonExpression):
        return _load_comparison_expression(value, 0, label_counter)
    if isinstance(value, ResolvedBooleanNotExpression):
        return _load_boolean_not_expression(value, 0, label_counter)
    assert isinstance(value, ResolvedBooleanBinaryExpression)
    return _load_boolean_binary_expression(value, 0, label_counter)


def _load_binary_expression(
    expression: ResolvedBinaryExpression,
    depth: int,
    label_counter: list[int],
) -> list[str]:
    temporary = f"expression_temporary_{depth}"
    lines = [
        f"    ; binary {expression.operator.value}: evaluate right operand",
        *_load_value_at_depth(expression.right, depth + 1, label_counter),
        f"    sta {temporary}",
        "    ; evaluate left operand",
        *_load_value_at_depth(expression.left, depth + 1, label_counter),
    ]
    if expression.operator is BinaryOperator.ADD:
        return [*lines, "    clc", f"    adc {temporary}"]
    return [*lines, "    sec", f"    sbc {temporary}"]


def _load_value_at_depth(
    value: ResolvedValue,
    depth: int,
    label_counter: list[int],
) -> list[str]:
    if isinstance(value, ResolvedBinaryExpression):
        return _load_binary_expression(value, depth, label_counter)
    if isinstance(value, ResolvedComparisonExpression):
        return _load_comparison_expression(value, depth, label_counter)
    if isinstance(value, ResolvedBooleanNotExpression):
        return _load_boolean_not_expression(value, depth, label_counter)
    if isinstance(value, ResolvedBooleanBinaryExpression):
        return _load_boolean_binary_expression(value, depth, label_counter)
    if isinstance(value, ResolvedUnaryExpression):
        lines = _load_value_at_depth(value.operand, depth, label_counter)
        if value.operator is UnaryOperator.PLUS:
            return [*lines, "    ; unary + leaves the byte unchanged"]
        return [
            *lines,
            "    eor #$FF                ; unary -: two's complement",
            "    clc",
            "    adc #$01",
        ]
    return _load_value(value, label_counter)


def _load_comparison_expression(
    expression: ResolvedComparisonExpression,
    depth: int,
    label_counter: list[int],
) -> list[str]:
    temporary = f"expression_temporary_{depth}"
    true_label = _new_label(label_counter, "comparison_true")
    false_label = _new_label(label_counter, "comparison_false")
    end_label = _new_label(label_counter, "comparison_end")
    lines = [
        f"    ; comparison {expression.operator.value}: evaluate right operand",
        *_load_value_at_depth(expression.right, depth + 1, label_counter),
        f"    sta {temporary}",
        "    ; evaluate left operand",
        *_load_value_at_depth(expression.left, depth + 1, label_counter),
        f"    cmp {temporary}",
    ]
    branches = {
        ComparisonOperator.EQUAL: [f"    beq {true_label}"],
        ComparisonOperator.NOT_EQUAL: [f"    bne {true_label}"],
        ComparisonOperator.LESS: [f"    bcc {true_label}"],
        ComparisonOperator.GREATER: [
            f"    beq {false_label}",
            f"    bcs {true_label}",
        ],
        ComparisonOperator.LESS_EQUAL: [
            f"    bcc {true_label}",
            f"    beq {true_label}",
        ],
        ComparisonOperator.GREATER_EQUAL: [f"    bcs {true_label}"],
    }
    return [
        *lines,
        *branches[expression.operator],
        f"{false_label}:",
        "    lda #$00              ; false",
        f"    jmp {end_label}",
        f"{true_label}:",
        "    lda #$01              ; true",
        f"{end_label}:",
    ]


def _load_boolean_not_expression(
    expression: ResolvedBooleanNotExpression,
    depth: int,
    label_counter: list[int],
) -> list[str]:
    true_label = _new_label(label_counter, "not_true")
    end_label = _new_label(label_counter, "not_end")
    return [
        "    ; boolean not",
        *_load_value_at_depth(expression.operand, depth, label_counter),
        "    cmp #$00",
        f"    beq {true_label}",
        "    lda #$00              ; false",
        f"    jmp {end_label}",
        f"{true_label}:",
        "    lda #$01              ; true",
        f"{end_label}:",
    ]


def _load_boolean_binary_expression(
    expression: ResolvedBooleanBinaryExpression,
    depth: int,
    label_counter: list[int],
) -> list[str]:
    evaluate_right_label = _new_label(label_counter, "boolean_evaluate_right")
    true_label = _new_label(label_counter, "boolean_true")
    false_label = _new_label(label_counter, "boolean_false")
    end_label = _new_label(label_counter, "boolean_end")
    lines = [
        f"    ; boolean {expression.operator.value}: evaluate left operand",
        *_load_value_at_depth(expression.left, depth, label_counter),
        "    cmp #$00",
    ]
    if expression.operator is BooleanOperator.AND:
        lines.extend(
            [
                f"    bne {evaluate_right_label}",
                f"    jmp {false_label}       ; short-circuit false",
            ]
        )
    else:
        lines.extend(
            [
                f"    beq {evaluate_right_label}",
                f"    jmp {true_label}        ; short-circuit true",
            ]
        )
    return [
        *lines,
        f"{evaluate_right_label}:",
        "    ; evaluate right operand",
        *_load_value_at_depth(expression.right, depth, label_counter),
        "    cmp #$00",
        f"    bne {true_label}",
        f"{false_label}:",
        "    lda #$00              ; false",
        f"    jmp {end_label}",
        f"{true_label}:",
        "    lda #$01              ; true",
        f"{end_label}:",
    ]


def _new_label(label_counter: list[int], prefix: str) -> str:
    label = f"@{prefix}_{label_counter[0]}"
    label_counter[0] += 1
    return label


def _expression_depth(value: ResolvedValue) -> int:
    if isinstance(value, (ResolvedBinaryExpression, ResolvedComparisonExpression)):
        return 1 + max(
            _expression_depth(value.left),
            _expression_depth(value.right),
        )
    if isinstance(value, (ResolvedUnaryExpression, ResolvedBooleanNotExpression)):
        return _expression_depth(value.operand)
    if isinstance(value, ResolvedBooleanBinaryExpression):
        return max(
            _expression_depth(value.left),
            _expression_depth(value.right),
        )
    return 0


def _statement_expression_depth(statement: ResolvedStatement) -> int:
    if isinstance(statement, ResolvedAssignment):
        return _expression_depth(statement.value)
    if isinstance(statement, ResolvedSetBackgroundColor):
        return _expression_depth(statement.argument)
    if isinstance(statement, ResolvedIncrementStatement):
        return (
            _expression_depth(statement.amount)
            if statement.amount is not None
            else 0
        )
    if isinstance(statement, ResolvedDecrementStatement):
        return (
            max(1, _expression_depth(statement.amount))
            if statement.amount is not None
            else 0
        )
    if isinstance(statement, ResolvedIfStatement):
        branch_depths = [
            _statement_expression_depth(branch_statement)
            for branch_statement in statement.then_branch
        ]
        if statement.else_branch is not None:
            branch_depths.extend(
                _statement_expression_depth(branch_statement)
                for branch_statement in statement.else_branch
            )
        return max(
            [_expression_depth(statement.condition), *branch_depths],
        )
    if isinstance(statement, (ResolvedWhileStatement, ResolvedRepeatStatement)):
        body_depths = [
            _statement_expression_depth(body_statement)
            for body_statement in statement.body
        ]
        return max(
            [_expression_depth(statement.condition), *body_depths],
        )
    if isinstance(statement, ResolvedForStatement):
        body_depths = [
            _statement_expression_depth(body_statement)
            for body_statement in statement.body
        ]
        return max(
            [
                _expression_depth(statement.initial),
                _expression_depth(statement.final),
                *body_depths,
            ],
        )
    return 0


def _count_for_statements(statement: ResolvedStatement) -> int:
    if isinstance(statement, ResolvedForStatement):
        return 1 + sum(
            _count_for_statements(body_statement)
            for body_statement in statement.body
        )
    if isinstance(statement, ResolvedIfStatement):
        count = sum(
            _count_for_statements(branch_statement)
            for branch_statement in statement.then_branch
        )
        if statement.else_branch is not None:
            count += sum(
                _count_for_statements(branch_statement)
                for branch_statement in statement.else_branch
            )
        return count
    if isinstance(statement, (ResolvedWhileStatement, ResolvedRepeatStatement)):
        return sum(
            _count_for_statements(body_statement)
            for body_statement in statement.body
        )
    return 0
