"""ca65 Assembly generation for an NROM-256 image."""

from .ast import (
    BuiltInType,
    ImmediateValue,
    ResolvedAssignment,
    ResolvedProgram,
    ResolvedSetBackgroundColor,
    ResolvedValue,
    Run,
    VariableValue,
)


def generate(program: ResolvedProgram) -> str:
    color_commands = [
        statement
        for statement in program.statements
        if isinstance(statement, ResolvedSetBackgroundColor)
    ]
    run_commands = [
        statement for statement in program.statements if isinstance(statement, Run)
    ]
    if len(color_commands) != 1 or len(run_commands) != 1:
        raise ValueError("invalid resolved AST for the current milestone")

    variable_lines = [
        f"{variable.label}: .res 1       ; {variable.name}: {variable.type.value}"
        for variable in program.variables
    ]
    if not variable_lines:
        variable_lines.append("    ; no variables")

    statement_lines: list[str] = []
    for statement in program.statements:
        if isinstance(statement, ResolvedAssignment):
            statement_lines.extend(
                [
                    "",
                    f"; Source: {statement.target.name} := value",
                    *_load_value(statement.value),
                    f"    sta {statement.target.label}",
                ]
            )
        elif isinstance(statement, ResolvedSetBackgroundColor):
            statement_lines.extend(
                [
                    "",
                    "; Source: nes.set_background_color(value)",
                    "    lda #$3F",
                    "    sta $2006               ; universal palette address, high byte",
                    "    lda #$00",
                    "    sta $2006               ; low byte",
                    *_load_value(statement.argument),
                    "    sta $2007",
                ]
            )
        else:
            assert isinstance(statement, Run)
            statement_lines.extend(
                [
                    "",
                    "; Source: nes.run",
                    "    lda #$00",
                    "    sta $2005               ; scroll X",
                    "    sta $2005               ; scroll Y",
                    "    lda #$08",
                    "    sta $2001               ; enable background rendering",
                    "",
                    "@main_loop:",
                    "    jmp @main_loop",
                ]
            )

    variables = "\n".join(variable_lines)
    statements = "\n".join(statement_lines)
    return f"""; Generated by nes-pascal for program {program.name}
; Mapper 0, 32 KiB PRG-ROM, 8 KiB CHR-ROM

.segment "HEADER"
    .byte "NES", $1A
    .byte 2                  ; 2 x 16 KiB PRG-ROM
    .byte 1                  ; 1 x 8 KiB CHR-ROM
    .byte $00                ; mapper 0, horizontal mirroring
    .byte $00                ; mapper 0
    .byte $00, $00, $00, $00, $00, $00, $00, $00

.segment "BSS"
; Source: variable declarations in regular CPU RAM
{variables}

.segment "CODE"

; Interrupt handlers
NMI:
    rti

IRQ:
    rti

; Source: implicit NES runtime initialization
RESET:
    sei
    cld
    ldx #$40
    stx $4017               ; disable frame counter IRQ
    ldx #$FF
    txs
    inx                     ; X = 0
    stx $2000               ; disable NMI
    stx $2001               ; disable rendering
    stx $4010               ; disable DMC IRQ
    bit $2002               ; clear the vblank latch

@wait_vblank_1:
    bit $2002
    bpl @wait_vblank_1

    txa
@clear_ram:
    sta $0000, x
    sta $0100, x
    sta $0200, x
    sta $0300, x
    sta $0400, x
    sta $0500, x
    sta $0600, x
    sta $0700, x
    inx
    bne @clear_ram

@wait_vblank_2:
    bit $2002
    bpl @wait_vblank_2
{statements}

.segment "VECTORS"
    .word NMI
    .word RESET
    .word IRQ

.segment "CHR"
    .res 8192, $00          ; empty CHR-ROM
"""


def _load_value(value: ResolvedValue) -> list[str]:
    if isinstance(value, ImmediateValue):
        if value.type is BuiltInType.BOOLEAN:
            description = "true" if value.value else "false"
            return [f"    lda #${value.value:02X}              ; {description}"]
        return [f"    lda #${value.value:02X}"]
    assert isinstance(value, VariableValue)
    return [f"    lda {value.variable.label}"]
